Repository ItoSeiy/2DShooting-first-grade, pull requests merged in 2021-12, with the labels that each got.

#33 自分用のフォルダを追加した
  Assets/6Kondo.meta
  Assets/6Kondo/Scenes.meta
  Assets/6Kondo/Scenes/KondoTest.unity
  Assets/6Kondo/Scenes/KondoTest.unity.meta
  Assets/6Kondo/Scripts.meta
  Assets/6Kondo/Scripts/KondoTest.cs
  Assets/6Kondo/Scripts/KondoTest.cs.meta
Labels: Test

#40 ゲームマネージャーを制作した
  Assets/1Ito/Scenes Ito/Test Ito.unity
  Assets/1Ito/Scripts Ito/GameManager.cs
  Assets/1Ito/Scripts Ito/GameManager.cs.meta
Labels: 機能作成完了

#45 BulletBaseを更新しました
  Assets/1Ito/Scripts Ito/BulletBese.cs
Labels: 機能 プログラム など :memo:, 機能の修正 :toolbox:, 完了 :ballot_box_with_check:

#44 3色のナイフ形弾幕のSpriteを自分のEnemyBulletSpritesフォルダに追加して星形弾幕のSpriteを和田に送りました
  Assets/6Kondo/Sprites.meta
  Assets/6Kondo/Sprites/EnemyBulletSprites.meta
  Assets/6Kondo/Sprites/EnemyBulletSprites/KnifeBlue.png
  Assets/6Kondo/Sprites/EnemyBulletSprites/KnifeBlue.png.meta
  Assets/6Kondo/Sprites/EnemyBulletSprites/KnifeRed.png
  Assets/6Kondo/Sprites/EnemyBulletSprites/KnifeRed.png.meta
  Assets/6Kondo/Sprites/EnemyBulletSprites/KnifeYellow.png
  Assets/6Kondo/Sprites/EnemyBulletSprites/KnifeYellow.png.meta
  Assets/6Kondo/Sprites/EnemyBulletSprites/Star.png
  Assets/6Kondo/Sprites/EnemyBulletSprites/Star.png.meta
  Assets/6Kondo/Sprites/PlayerBulletSprites.meta
Labels: 仕様 デザイン など :art:, 完了 :ballot_box_with_check:

#50 ゲームマネージャーの修正
  Assets/1Ito/Scripts Ito/GameManager.cs
Labels: 機能 プログラム など :memo:, 未完了 :x:

#46 アイテムと弾幕スプライトが完成した
  Assets/3Wada/Prefabs.meta
  Assets/3Wada/Prefabs/EnemyBulletPrefabs.meta
  Assets/3Wada/Prefabs/EnemyBulletPrefabs/Danmaku.prefab
  Assets/3Wada/Prefabs/EnemyBulletPrefabs/Danmaku.prefab.meta
  Assets/3Wada/Prefabs/EnemyBulletPrefabs/YellowBullet.prefab
  Assets/3Wada/Prefabs/EnemyBulletPrefabs/YellowBullet.prefab.meta
  Assets/3Wada/Prefabs/ItemPrefabs.meta
  Assets/3Wada/Prefabs/ItemPrefabs/Boom.prefab
  Assets/3Wada/Prefabs/ItemPrefabs/Boom.prefab.meta
  Assets/3Wada/Prefabs/ItemPrefabs/Point.prefab
  Assets/3Wada/Prefabs/ItemPrefabs/Point.prefab.meta
  Assets/3Wada/Prefabs/ItemPrefabs/Power.prefab
  Assets/3Wada/Prefabs/ItemPrefabs/Power.prefab.meta
  Assets/3Wada/Prefabs/PlayerBulletPrefabs.meta
  Assets/3Wada/Prefabs/PlayerBulletPrefabs/Fire.prefab
  Assets/3Wada/Prefabs/PlayerBulletPrefabs/Fire.prefab.meta
  Assets/3Wada/Prefabs/PlayerBulletPrefabs/IceBall.prefab
  Assets/3Wada/Prefabs/PlayerBulletPrefabs/IceBall.prefab.meta
  Assets/3Wada/Prefabs/PlayerBulletPrefabs/RedBullet.prefab
  Assets/3Wada/Prefabs/PlayerBulletPrefabs/RedBullet.prefab.meta
  Assets/3Wada/Scenes Wada/Test Wada.unity
  Assets/3Wada/Sprites.meta
  Assets/3Wada/Sprites/EnemyBulletSprites.meta
  Assets/3Wada/Sprites/EnemyBulletSprites/Danmaku.png
  Assets/3Wada/Sprites/EnemyBulletSprites/Danmaku.png.meta
  Assets/3Wada/Sprites/EnemyBulletSprites/YellowBullet.png
  Assets/3Wada/Sprites/EnemyBulletSprites/YellowBullet.png.meta
  Assets/3Wada/Sprites/ItemSprites.meta
  Assets/3Wada/Sprites/ItemSprites/Boom.png
  Assets/3Wada/Sprites/ItemSprites/Boom.png.meta
  Assets/3Wada/Sprites/ItemSprites/Point.png
  Assets/3Wada/Sprites/ItemSprites/Point.png.meta
  Assets/3Wada/Sprites/ItemSprites/power.png
  Assets/3Wada/Sprites/ItemSprites/power.png.meta
  Assets/3Wada/Sprites/Player BulletSprites.meta
  Assets/3Wada/Sprites/Player BulletSprites/Fire.png
  Assets/3Wada/Sprites/Player BulletSprites/Fire.png.meta
  Assets/3Wada/Sprites/Player BulletSprites/Red Bullet.png
  Assets/3Wada/Sprites/Player BulletSprites/Red Bullet.png.meta
  Assets/3Wada/Sprites/Player BulletSprites/iceBoll.png
  Assets/3Wada/Sprites/Player BulletSprites/iceBoll.png.meta
Labels: 仕様 デザイン など :art:, 完了 :ballot_box_with_check:

#55 PlayerBombを完成させた
  Assets/6Kondo/Scenes/KondoTest.unity
  Assets/6Kondo/Scripts/PlayerBomb.cs
  Assets/6Kondo/Scripts/PlayerBomb.cs.meta
  Assets/6Kondo/Sprites/EnemyBulletSprites/Materials.meta
  Assets/6Kondo/Sprites/EnemyBulletSprites/Materials/KnifeRed.mat
  Assets/6Kondo/Sprites/EnemyBulletSprites/Materials/KnifeRed.mat.meta
Labels: 機能 プログラム など :memo:, 完了 :ballot_box_with_check:

#61 EnemyBaseクラスの修正(未完成)
  Assets/1Ito/Scripts Ito/EnemyBese.cs
  Assets/1Ito/Scripts Ito/TestEnemy.cs
Labels: 機能 プログラム など :memo:, 機能の修正 :toolbox:, 未完了 :x:

#62 インターフェースを制作した
  Assets/1Ito/Scripts Ito/GameManager.cs
  Assets/1Ito/Scripts Ito/IDamage.cs
  Assets/1Ito/Scripts Ito/IDamage.cs.meta
Labels: 機能 プログラム など :memo:, 完了 :ballot_box_with_check:

#63 BulletBaseの修正(未完成)
  Assets/1Ito/Scripts Ito/BulletBese.cs
Labels: 機能 プログラム など :memo:, 機能の修正 :toolbox:, 未完了 :x:

#64 Bulletを修正中
  Assets/1Ito/Scripts Ito/BulletBese.cs
  Assets/1Ito/Scripts Ito/TestBullet.cs
Labels: 機能 プログラム など :memo:, 機能の修正 :toolbox:, 未完了 :x:

#65 BulletBaseを修正中
  Assets/1Ito/Scripts Ito/BulletBese.cs
  Assets/1Ito/Scripts Ito/TestBullet.cs
Labels: 機能 プログラム など :memo:, 機能の修正 :toolbox:, 未完了 :x:

#66 EnemyBaseを修正中
  Assets/1Ito/Scenes Ito/Test Ito.unity
  Assets/1Ito/Scripts Ito/EnemyBese.cs
  Assets/1Ito/Scripts Ito/TestEnemy.cs
Labels: 機能 プログラム など :memo:, 機能の修正 :toolbox:, 未完了 :x:

#67 Lifeのスプライトを追加した
  Assets/3Wada/Prefabs/ItemPrefabs/Bomb.prefab
  Assets/3Wada/Prefabs/ItemPrefabs/Bomb.prefab.meta
  Assets/3Wada/Prefabs/ItemPrefabs/Life.prefab
  Assets/3Wada/Prefabs/ItemPrefabs/Life.prefab.meta
  Assets/3Wada/Scenes Wada/Test Wada.unity
  Assets/3Wada/Sprites/ItemSprites/Life.png
  Assets/3Wada/Sprites/ItemSprites/Life.png.meta
  Assets/6Kondo/Sprites/EnemyBulletSprites/Materials.meta
Labels: 仕様 デザイン など :art:, 完了 :ballot_box_with_check:

#68 フォルダの整理を行いました(Bombは製作途中です)
  Assets/6Kondo/Plefabs/Materials.meta
  Assets/6Kondo/Plefabs/Materials/Explosion.mat
  Assets/6Kondo/Plefabs/Materials/Explosion.mat.meta
  Assets/6Kondo/Scenes/KondoTest.unity
  Assets/6Kondo/Scripts/Bomb.meta
  Assets/6Kondo/Scripts/Bomb/BombChildBullet.cs
  Assets/6Kondo/Scripts/Bomb/BombChildBullet.cs.meta
  Assets/6Kondo/Scripts/Bomb/KondoTest.cs
  Assets/6Kondo/Scripts/Bomb/KondoTest.cs.meta
  Assets/6Kondo/Sprites/Explosion.meta
  Assets/6Kondo/Sprites/Explosion/ExplosionSprite.png
  Assets/6Kondo/Sprites/Explosion/ExplosionSprite.png.meta
Labels: 機能 プログラム など :memo:, 機能の修正 :toolbox:, 未完了 :x:

#69 スクリプトの名前変更やフォルダーの整理を行った(BulleBaseは修正中です)
  Assets/1Ito/Scripts Ito/Bullet.meta
  Assets/1Ito/Scripts Ito/Bullet/BulletBese.cs
  Assets/1Ito/Scripts Ito/Bullet/BulletBese.cs.meta
  Assets/1Ito/Scripts Ito/Bullet/TestBullet01.cs
  Assets/1Ito/Scripts Ito/Bullet/TestBullet01.cs.meta
  Assets/1Ito/Scripts Ito/Bullet/TestBullet02.cs
  Assets/1Ito/Scripts Ito/Bullet/TestBullet02.cs.meta
  Assets/1Ito/Scripts Ito/Enemy.meta
  Assets/1Ito/Scripts Ito/Enemy/EnemyBese.cs
  Assets/1Ito/Scripts Ito/Enemy/EnemyBese.cs.meta
  Assets/1Ito/Scripts Ito/Enemy/TestEnemy01.cs
  Assets/1Ito/Scripts Ito/Enemy/TestEnemy01.cs.meta
  Assets/1Ito/Scripts Ito/Interface.meta
  Assets/1Ito/Scripts Ito/Interface/IDamage.cs
  Assets/1Ito/Scripts Ito/Interface/IDamage.cs.meta
Labels: 機能 プログラム など :memo:, 機能の修正 :toolbox:, 未完了 :x:

#71 Bulletの修正を完了した
  Assets/1Ito/Scenes Ito/Test Ito.unity
  Assets/1Ito/Scripts Ito/Bullet/BulletBese.cs
  Assets/1Ito/Scripts Ito/Bullet/TestBullet01.cs
  Assets/1Ito/Scripts Ito/Bullet/TestBullet02.cs
Labels: 機能 プログラム など :memo:, 機能の修正 :toolbox:, 完了 :ballot_box_with_check:

#73 BulletBaseの修正
  Assets/1Ito/Scripts Ito/Bullet/BulletBese.cs
Labels: 機能 プログラム など :memo:, 機能の修正 :toolbox:, 完了 :ballot_box_with_check:

#75 spriteの大きさと位置の調整完了
  Assets/3Wada/Prefabs.meta
  Assets/3Wada/Prefabs/EnemyBulletPrefabs.meta
  Assets/3Wada/Prefabs/EnemyBulletPrefabs/Danmaku.prefab
  Assets/3Wada/Prefabs/EnemyBulletPrefabs/Danmaku.prefab.meta
  Assets/3Wada/Prefabs/EnemyBulletPrefabs/YellowBullet.prefab
  Assets/3Wada/Prefabs/EnemyBulletPrefabs/YellowBullet.prefab.meta
  Assets/3Wada/Prefabs/ItemPrefabs.meta
  Assets/3Wada/Prefabs/ItemPrefabs/Bomb.prefab
  Assets/3Wada/Prefabs/ItemPrefabs/Bomb.prefab.meta
  Assets/3Wada/Prefabs/ItemPrefabs/Life.prefab
  Assets/3Wada/Prefabs/ItemPrefabs/Life.prefab.meta
  Assets/3Wada/Prefabs/ItemPrefabs/Point.prefab
  Assets/3Wada/Prefabs/ItemPrefabs/Point.prefab.meta
  Assets/3Wada/Prefabs/ItemPrefabs/Power.prefab
  Assets/3Wada/Prefabs/ItemPrefabs/Power.prefab.meta
  Assets/3Wada/Prefabs/PlayerBulletPrefabs.meta
  Assets/3Wada/Prefabs/PlayerBulletPrefabs/Fire.prefab
  Assets/3Wada/Prefabs/PlayerBulletPrefabs/Fire.prefab.meta
  Assets/3Wada/Prefabs/PlayerBulletPrefabs/IceBall.prefab
  Assets/3Wada/Prefabs/PlayerBulletPrefabs/IceBall.prefab.meta
  Assets/3Wada/Prefabs/PlayerBulletPrefabs/RedBullet.prefab
  Assets/3Wada/Prefabs/PlayerBulletPrefabs/RedBullet.prefab.meta
  Assets/3Wada/Scenes Wada/Test Wada.unity
  Assets/3Wada/Sprites/EnemyBulletSprites/Danmaku.png
  Assets/3Wada/Sprites/EnemyBulletSprites/Enemy_RedBullet.png
  Assets/3Wada/Sprites/EnemyBulletSprites/Enemy_RedBullet.png.meta
  Assets/3Wada/Sprites/EnemyBulletSprites/Enemy_YellowBullet.png
  Assets/3Wada/Sprites/EnemyBulletSprites/Enemy_YellowBullet.png.meta
  Assets/3Wada/Sprites/EnemyBulletSprites/YellowBullet.png
  Assets/3Wada/Sprites/ItemSprites/Bomb.png
  Assets/3Wada/Sprites/ItemSprites/Bomb.png.meta
  Assets/3Wada/Sprites/ItemSprites/Boom.png
  Assets/3Wada/Sprites/ItemSprites/Life.png
  Assets/3Wada/Sprites/ItemSprites/Life.png.meta
  Assets/3Wada/Sprites/ItemSprites/Point.png
  Assets/3Wada/Sprites/ItemSprites/Point.png.meta
  Assets/3Wada/Sprites/ItemSprites/power.png
  Assets/3Wada/Sprites/ItemSprites/power.png.meta
  Assets/3Wada/Sprites/Player BulletSprites/Fire.png
  Assets/3Wada/Sprites/Player BulletSprites/Fire.png.meta
  Assets/3Wada/Sprites/Player BulletSprites/Player_RedBullet.png
  Assets/3Wada/Sprites/Player BulletSprites/Player_RedBullet.png.meta
  Assets/3Wada/Sprites/Player BulletSprites/Red Bullet.png
  Assets/3Wada/Sprites/Player BulletSprites/iceBoll.png
  Assets/3Wada/Sprites/Player BulletSprites/iceBoll.png.meta
Labels: 仕様 デザイン など :art:, 完了 :ballot_box_with_check:

#80 BulletBaseクラスを修正した
  Assets/1Ito/Scenes Ito/Test Ito.unity
  Assets/1Ito/Scripts Ito/Bullet/BulletBese.cs
  Assets/1Ito/Scripts Ito/Enemy/TestEnemy02.cs
Labels: 機能 プログラム など :memo:, 機能の修正 :toolbox:, 未完了 :x:

#81 ゲームマネージャーの修正を行った
  Assets/1Ito/Scripts Ito/GameManager.cs
Labels: 機能 プログラム など :memo:, 機能の修正 :toolbox:, 完了 :ballot_box_with_check:

#83 バージョンアップを行った
  Assets/1Ito/Scripts Ito/Bullet/BulletPool.cs
  Assets/1Ito/Scripts Ito/Bullet/BulletPool.cs.meta
  Assets/1Ito/Scripts Ito/Bullet/BulletSettings.cs
  Assets/1Ito/Scripts Ito/Bullet/BulletSettings.cs.meta
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/ProjectVersion.txt
  ProjectSettings/VersionControlSettings.asset
  UserSettings/EditorUserSettings.asset
Labels: 機能 プログラム など :memo:

#84 エラーの修正です
  Assets/1Ito/Scripts Ito/Bullet/BulletPool.cs
Labels: 機能 プログラム など :memo:, 機能の修正 :toolbox:

#85 Feature/title
  Assets/4Kojima/Object.meta
  Assets/4Kojima/Object/Cube R.mat
  Assets/4Kojima/Object/Cube R.mat.meta
  Assets/4Kojima/Object/Cube.prefab
  Assets/4Kojima/Object/Cube.prefab.meta
  Assets/4Kojima/Scenes Kojima/Test Kojima.unity
  Assets/4Kojima/Scenes Kojima/Title_Kojima.unity
  Assets/4Kojima/Timeline.meta
  Assets/4Kojima/Timeline/Title.playable
  Assets/4Kojima/Timeline/Title.playable.meta
Labels: Test

#87 チャージショットを実装した
  Assets/2Kanbara/Prefab Kanbara.meta
  Assets/2Kanbara/Prefab Kanbara/Muzzle.prefab
  Assets/2Kanbara/Prefab Kanbara/Muzzle.prefab.meta
  Assets/2Kanbara/Prefab Kanbara/RespawnPoint.prefab
  Assets/2Kanbara/Prefab Kanbara/RespawnPoint.prefab.meta
  Assets/2Kanbara/Prefab Kanbara/TestBullet.prefab
  Assets/2Kanbara/Prefab Kanbara/TestBullet.prefab.meta
  Assets/2Kanbara/Scenes Kanbara/Prayer movement.unity
  Assets/2Kanbara/Scripts Kanbara/Player.meta
  Assets/2Kanbara/Scripts Kanbara/Player/Player1.cs
  Assets/2Kanbara/Scripts Kanbara/Player/Player1.cs.meta
  Assets/2Kanbara/Scripts Kanbara/Player/Player2.cs
  Assets/2Kanbara/Scripts Kanbara/Player/Player2.cs.meta
  Assets/2Kanbara/Scripts Kanbara/Player/PlayerBase.cs
  Assets/2Kanbara/Scripts Kanbara/Player/PlayerBase.cs.meta
  Assets/2Kanbara/Scripts Kanbara/PlayerController.cs
  Assets/2Kanbara/Scripts Kanbara/TestBulletController.cs
  Assets/2Kanbara/Scripts Kanbara/TestBulletController.cs.meta
  ProjectSettings/InputManager.asset
Labels: 機能 プログラム など :memo:, 機能の修正 :toolbox:, 未完了 :x:

#89 PlayerBulletを完成させました
  Assets/5Adachi/Prefab.meta
  Assets/5Adachi/Prefab/Player01BulletStraightPrefabs.meta
  Assets/5Adachi/Prefab/Player01BulletStraightPrefabs/Player01Power01StraightBullet.prefab
  Assets/5Adachi/Prefab/Player01BulletStraightPrefabs/Player01Power01StraightBullet.prefab.meta
  Assets/5Adachi/Prefab/Player01BulletStraightPrefabs/Player01Power02StraightBullet.prefab
  Assets/5Adachi/Prefab/Player01BulletStraightPrefabs/Player01Power02StraightBullet.prefab.meta
  Assets/5Adachi/Prefab/Player01BulletStraightPrefabs/Player01Power03StraightBullet.prefab
  Assets/5Adachi/Prefab/Player01BulletStraightPrefabs/Player01Power03StraightBullet.prefab.meta
  Assets/5Adachi/Prefab/Player02BulletFollow.meta
  Assets/5Adachi/Prefab/Player02BulletFollow/Player02Power01FollowBullet.prefab
  Assets/5Adachi/Prefab/Player02BulletFollow/Player02Power01FollowBullet.prefab.meta
  Assets/5Adachi/Prefab/Player02BulletFollow/Player02Power02FollowBullet.prefab
  Assets/5Adachi/Prefab/Player02BulletFollow/Player02Power02FollowBullet.prefab.meta
  Assets/5Adachi/Prefab/Player02BulletFollow/Player02Power03FollowBullet.prefab
  Assets/5Adachi/Prefab/Player02BulletFollow/Player02Power03FollowBullet.prefab.meta
  Assets/5Adachi/Scenes/TestSceneAdachi.unity
  Assets/5Adachi/Scripts/BulletScripts.meta
  Assets/5Adachi/Scripts/BulletScripts/PlayerBulletFollow.cs
  Assets/5Adachi/Scripts/BulletScripts/PlayerBulletFollow.cs.meta
  Assets/5Adachi/Scripts/BulletScripts/PlayerBulletStraight.cs
  Assets/5Adachi/Scripts/BulletScripts/PlayerBulletStraight.cs.meta
  Assets/5Adachi/Scripts/TestAdachi.cs
Labels: 機能 プログラム など :memo:, 完了 :ballot_box_with_check:
