Repository ItoSeiy/2DShooting-first-grade, pull requests merged in 2022-03, with the labels that each got.

#167 InputAction不具合修正
  Assets/2Kanbara/InputSystem/2DShooting Late presentation.inputactions
Labels: 機能 プログラム など :memo:, 不具合修正 :wrench:, 未完了 :x:

#169 InputAction不具合修正
  Assets/2Kanbara/InputSystem/2DShooting Late presentation.inputactions
Labels: 機能 プログラム など :memo:, 不具合修正 :wrench:, 完了 :ballot_box_with_check:

#170 InputSystem不具合修正
  Assets/2Kanbara/InputSystem/2DShooting Late presentation.inputactions
  Assets/2Kanbara/Scripts Kanbara/Player/PlayerBase.cs
Labels: 不具合修正 :wrench:, 未完了 :x:

#171 キーバインドにZキーを追加
  Assets/2Kanbara/InputSystem/2DShooting Late presentation.inputactions
Labels: 不具合修正 :wrench:, 機能の修正 :toolbox:, 完了 :ballot_box_with_check:

#173 小島フォルダ整理
  Assets/4Kojima/Scenes.meta
  Assets/4Kojima/Scenes/Test Kojima.unity
  Assets/4Kojima/Scenes/Test Kojima.unity.meta
  Assets/4Kojima/Scenes/Title_Kojima.unity
  Assets/4Kojima/Scenes/Title_Kojima.unity.meta
  Assets/4Kojima/Scenes/Win&Lose_Kojima.unity
  Assets/4Kojima/Scenes/Win&Lose_Kojima.unity.meta
  Assets/4Kojima/Scripts.meta
  Assets/4Kojima/Scripts/ScoreCounte.cs
  Assets/4Kojima/Scripts/ScoreCounte.cs.meta
  Assets/4Kojima/Scripts/Test Kojima.cs
  Assets/4Kojima/Scripts/Test Kojima.cs.meta
Labels: Test

#174 チュートリアルの修正
  Assets/6Kondo/Prefabs/TutorialControllerManager.prefab
  Assets/6Kondo/Prefabs/TutorialControllerManager.prefab.meta
  Assets/6Kondo/Prefabs/TutorialEnemy.prefab
  Assets/6Kondo/Prefabs/TutorialEnemy.prefab.meta
  Assets/6Kondo/Prefabs/TutorialKeybordManager.prefab
  Assets/6Kondo/Prefabs/TutorialKeybordManager.prefab.meta
  Assets/6Kondo/Scripts/TutorialEnamy.cs
  Assets/6Kondo/Scripts/TutorialEnamy.cs.meta
  Assets/6Kondo/Sound/TutorialClearSound.wav
  Assets/6Kondo/Sound/TutorialClearSound.wav.meta
  Assets/6Kondo/Sound/TutorialTaskClearSound.wav
  Assets/MasterScene/Tutorial/ControllerTutorialPlayer1Stage.unity
  Assets/MasterScene/Tutorial/ControllerTutorialPlayer2Stage.unity
  Assets/MasterScene/Tutorial/KeybordTutorialPlayer1Stage.unity
  Assets/MasterScene/Tutorial/KeybordTutorialPlayer2Stage.unity
Labels: 機能 プログラム など :memo:, 不具合修正 :wrench:, 機能の修正 :toolbox:, 完了 :ballot_box_with_check:

#175 チュートリアル修正
  Assets/MasterScene/Tutorial/ControllerTutorialPlayer2Stage.unity
  Assets/MasterScene/Tutorial/KeybordTutorialPlayer1Stage.unity
Labels: 不具合発見 :bug:, 不具合修正 :wrench:, 完了 :ballot_box_with_check:

#187 ポーズUI完成
  Assets/6Kondo/Prefabs/PausePanel.prefab
  Assets/6Kondo/Prefabs/PausePanel.prefab.meta
  Assets/6Kondo/Scenes/Pause UI.unity
  Assets/6Kondo/Scenes/Pause UI.unity.meta
  Assets/6Kondo/Scenes/UITest.unity
Labels: 仕様 デザイン など :art:, 完了 :ballot_box_with_check:

#189 フェイズマネージャー修正完了
  Assets/1Ito/Prefabs/===Managers===.prefab
  Assets/1Ito/Prefabs/TestEnemy.prefab
  Assets/1Ito/ScenesIto/TestIto.unity
  Assets/1Ito/Scripts Ito/Boss/BossController.cs
  Assets/1Ito/Scripts Ito/Boss/BossData.cs
  Assets/1Ito/Scripts Ito/Enemy/EnemyBase.cs
  Assets/1Ito/Scripts Ito/Manager/PhaseNovelManager.cs
  Assets/1Ito/Scripts Ito/Manager/SoundManager.cs
  Assets/1Ito/Scripts Ito/Novel/GSSReader.cs
  Assets/1Ito/Scripts Ito/Novel/NovelRenderer.cs
  Assets/1Ito/Scripts Ito/ObjectPool/ObjectPool.cs
  Assets/1Ito/Scripts Ito/ScriptableObject/StageParam.cs
  Assets/2Kanbara/Prefab Kanbara/Player/Player1.prefab
  Assets/2Kanbara/Prefab Kanbara/Player/Player2.prefab
  Assets/2Kanbara/Scripts Kanbara/Player/PlayerBase.cs
  Assets/3Wada/Enemy/EnemyPrefab/Enemy/DownEnemy.prefab
  Assets/3Wada/Enemy/EnemyPrefab/Enemy/LeftEnemy.prefab
  Assets/3Wada/Enemy/EnemyPrefab/Enemy/RightEnemy.prefab
  Assets/3Wada/Enemy/EnemyPrefab/Enemy/UpEnemy.prefab
  Assets/3Wada/Enemy/EnemyPrefab/MasterEnemy/Stage1/Stage1Phase1.prefab
  Assets/3Wada/Enemy/EnemyPrefab/MasterEnemy/Stage1/Stage1Phase2.prefab
  Assets/3Wada/Enemy/EnemyPrefab/MasterEnemy/Stage1/Stage1Phase3.prefab
  Assets/3Wada/Enemy/EnemyPrefab/TestEnemyBullet/EnemyFastAutoBullet.prefab
  Assets/3Wada/Enemy/EnemyPrefab/TestEnemyBullet/EnemyFastAutoBullet.prefab.meta
  Assets/3Wada/Enemy/EnemyPrefab/TestEnemyBullet/EnemyStraightDownBullet.prefab
  Assets/3Wada/Enemy/EnemyPrefab/TestEnemyBullet/EnemyStraightDownBullet.prefab.meta
  Assets/3Wada/Enemy/EnemyPrefab/TestEnemyBullet/EnemyStraightLeftBullet.prefab
  Assets/3Wada/Enemy/EnemyPrefab/TestEnemyBullet/EnemyStraightLeftBullet.prefab.meta
  Assets/3Wada/Enemy/EnemyPrefab/TestEnemyBullet/EnemyStraightRightBullet.prefab
  Assets/3Wada/Enemy/EnemyPrefab/TestEnemyBullet/EnemyStraightRightBullet.prefab.meta
  Assets/3Wada/Enemy/EnemyPrefab/TestEnemyBullet/EnemyStraightUpBullet.prefab
  Assets/3Wada/Enemy/EnemyPrefab/TestEnemyBullet/EnemyStraightUpBullet.prefab.meta
  Assets/3Wada/Enemy/EnemyScripts/EnemyController.cs
  Assets/3Wada/Scenes Wada/EnemyMove.unity
  Assets/3Wada/Sprites/ItemSprites/Bomb.png.meta
  Assets/3Wada/Sprites/ItemSprites/Point.png.meta
  Assets/3Wada/Sprites/ItemSprites/invincible.png.meta
  Assets/3Wada/Sprites/ItemSprites/power.png.meta
  Assets/4Kojima/Prefab/GameOverClear.meta
  Assets/4Kojima/Prefab/GameOverClear/Canvas GameClear.prefab
  Assets/4Kojima/Prefab/GameOverClear/Canvas GameClear.prefab.meta
  Assets/4Kojima/Prefab/GameOverClear/Canvas GameOver.prefab
  Assets/4Kojima/Prefab/GameOverClear/Canvas GameOver.prefab.meta
  Assets/4Kojima/Prefab/PL1/Canvas GameOver P1.prefab
  Assets/4Kojima/Prefab/PL2.meta
  Assets/4Kojima/Prefab/PL2/Canvas GameClear P2.prefab.meta
  Assets/4Kojima/Prefab/PL2/Canvas GameOver P2.prefab
  Assets/4Kojima/Prefab/PL2/Canvas GameOver P2.prefab.meta
  Assets/4Kojima/Scripts/ScoreCounte.cs
  Assets/4Kojima/Scripts/TextValueChange.cs
  Assets/4Kojima/Scripts/TextValueChange.cs.meta
  Assets/4Kojima/timeline/TimeLineWinOrLoseTimeline.playable
  Assets/6Kondo/Prefabs/UIManager.prefab
  Assets/MasterScene/Stage1/Stage1Player1.unity
  Assets/MasterScene/Stage1/Stage1Player2.unity
  ProjectSettings/Physics2DSettings.asset
  UserSettings/EditorUserSettings.asset
Labels: 機能 プログラム など :memo:, 機能の修正 :toolbox:, 完了 :ballot_box_with_check:

#192 くみ上げwip
  Assets/1Ito/Prefabs/===Managers===.prefab
  Assets/1Ito/Scripts Ito/Boss/BossController.cs
  Assets/1Ito/Scripts Ito/Enemy/EnemyBase.cs
  Assets/1Ito/Scripts Ito/Manager/GameManager.cs
  Assets/1Ito/Scripts Ito/Manager/PhaseNovelManager.cs
  Assets/1Ito/Scripts Ito/ScriptableObject/PoolObjectParam.asset
  Assets/2Kanbara/Scripts Kanbara/Player/PlayerBase.cs
  Assets/3Wada/Enemy/EnemyPrefab/MasterEnemy/Stage1/Stage1Phase2.prefab
  Assets/3Wada/Enemy/EnemyPrefab/MasterEnemy/Stage1/Stage1Phase3.prefab
  Assets/3Wada/Enemy/EnemyPrefab/MasterEnemy/Stage2/Stage2Phase1.prefab
  Assets/3Wada/Enemy/EnemyPrefab/MasterEnemy/Stage2/Stage2Phase2.prefab
  Assets/3Wada/Enemy/EnemyPrefab/MasterEnemy/Stage2/Stage2Phase3.prefab
  Assets/3Wada/Enemy/EnemyPrefab/MasterEnemy/Stage2/Stage2Phase4.prefab
  Assets/3Wada/Enemy/EnemyPrefab/MasterEnemy/Stage3/Stage3Phase1.prefab
  Assets/3Wada/Enemy/EnemyPrefab/MasterEnemy/Stage3/Stage3Phase2.prefab
  Assets/3Wada/Enemy/EnemyPrefab/MasterEnemy/Stage3/Stage3Phase3.prefab
  Assets/3Wada/Enemy/EnemyPrefab/MasterEnemy/Stage4/Stage4Phase1.prefab
  Assets/3Wada/Enemy/EnemyPrefab/MasterEnemy/Stage4/Stage4Phase2.prefab
  Assets/3Wada/Enemy/EnemyPrefab/MasterEnemy/Stage4/Stege4Phase3.prefab
  Assets/3Wada/Enemy/EnemyPrefab/MasterEnemy/Stage5/Stege5Phase1.prefab
  Assets/3Wada/Enemy/EnemyPrefab/MasterEnemy/Stage5/Stege5Phase2.prefab
  Assets/3Wada/Enemy/EnemyPrefab/MasterEnemy/Stage5/Stege5Phase3.prefab
  Assets/3Wada/Enemy/EnemyPrefab/MasterEnemy/Stage5/Stege5Phase4.prefab
  Assets/3Wada/Enemy/EnemyScripts/EnemyController.cs
  Assets/4Kojima/Prefab/GameOverClear/Canvas GameClear.prefab
  Assets/4Kojima/Prefab/GameOverClear/Canvas GameOver.prefab
  Assets/4Kojima/Scripts/TextValueChange.cs
  Assets/5Adachi/Scripts/BossSuperAttack/SuperAttackDelayFollow.cs
  Assets/MasterScene/Stage1/Stage1Player1.unity
  Assets/MasterScene/Stage1/Stage1Player2.unity
  Assets/MasterScene/Stage2/Stage2Player1.unity
  Assets/MasterScene/Stage2/Stage2Player2.unity
  Assets/MasterScene/Stage3/Stage3Player1.unity
  Assets/MasterScene/Stage3/Stage3Player2.unity
  Assets/MasterScene/Stage4/Stage4Player1.unity
  UserSettings/EditorUserSettings.asset
Labels: 機能 プログラム など :memo:, 未完了 :x:

#194 ポーズに関するインターフェースを基底クラスに継承させた
  Assets/1Ito/Scripts Ito/Bullet/BulletBese.cs
  Assets/1Ito/Scripts Ito/Enemy/EnemyBase.cs
  Assets/2Kanbara/Scenes Kanbara/Settings.unity
  Assets/2Kanbara/Scenes Kanbara/Settings.unity.meta
  Assets/2Kanbara/Scripts Kanbara/Item/ItemBase.cs
  Assets/2Kanbara/Scripts Kanbara/KeyConfig.meta
  Assets/2Kanbara/Scripts Kanbara/KeyConfig/InputManager.cs
  Assets/2Kanbara/Scripts Kanbara/KeyConfig/InputManager.cs.meta
  Assets/2Kanbara/Scripts Kanbara/KeyConfig/KeyConfig.cs
  Assets/2Kanbara/Scripts Kanbara/KeyConfig/KeyConfig.cs.meta
  Assets/2Kanbara/Scripts Kanbara/KeyConfig/PauseManager.cs
  Assets/2Kanbara/Scripts Kanbara/KeyConfig/PauseManager.cs.meta
  Assets/2Kanbara/Scripts Kanbara/KeyConfig/ReBindingUI.cs
  Assets/2Kanbara/Scripts Kanbara/KeyConfig/ReBindingUI.cs.meta
  Assets/2Kanbara/Scripts Kanbara/KeyConfig/RebindJumping.cs
  Assets/2Kanbara/Scripts Kanbara/KeyConfig/RebindJumping.cs.meta
  Assets/2Kanbara/Scripts Kanbara/KeyConfig/SaveBindings.cs
  Assets/2Kanbara/Scripts Kanbara/KeyConfig/SaveBindings.cs.meta
  Assets/2Kanbara/Scripts Kanbara/Pause.meta
  Assets/2Kanbara/Scripts Kanbara/Pause/IPauseable.cs
  Assets/2Kanbara/Scripts Kanbara/Pause/IPauseable.cs.meta
  Assets/2Kanbara/Scripts Kanbara/Player/PlayerBase.cs
  Assets/2Kanbara/Scripts Kanbara/Test Kanbara.cs
Labels: 機能 プログラム など :memo:, 不具合修正 :wrench:, 機能の修正 :toolbox:, 未完了 :x:

#197 組み込みwip
  Assets/1Ito/Audio/AudioPrefab/Boss03Killed.prefab
  Assets/1Ito/Audio/AudioPrefab/Boss03Killed.prefab.meta
  Assets/1Ito/Audio/AudioPrefab/BossKilled.prefab
  Assets/1Ito/Audio/AudioPrefab/BossKilled.prefab.meta
  Assets/1Ito/Prefabs/===Managers===.prefab
  Assets/1Ito/Prefabs/GameManager.prefab
  Assets/1Ito/Scripts Ito/Boss/BossController.cs
  Assets/1Ito/Scripts Ito/Enemy/EnemyBase.cs
  Assets/2Kanbara/InputSystem/2DShooting Late presentation.inputactions
  Assets/2Kanbara/Scripts Kanbara/KeyConfig/PauseManager.cs
  Assets/3Wada/Enemy/EnemyPrefab/MasterEnemy/Stage2/Stage2Phase3.prefab
  Assets/3Wada/Enemy/EnemyPrefab/MasterEnemy/Stage5/Stege5Phase4.prefab
  Assets/3Wada/Enemy/EnemyScripts/EnemyController.cs
  Assets/5Adachi/Sound/Boss03Killed.mp3.meta
  Assets/5Adachi/Sound/BossKilled.mp3.meta
  Assets/MasterScene/Stage1/Stage1Player1.unity
  Assets/MasterScene/Stage1/Stage1Player2.unity
  Assets/MasterScene/Stage2/Stage2Player1.unity
  Assets/MasterScene/Stage2/Stage2Player2.unity
  Assets/MasterScene/Stage3/Stage3Player1.unity
  Assets/MasterScene/Stage3/Stage3Player2.unity
  Assets/MasterScene/Stage4/Stage4Player1.unity
  Assets/MasterScene/Stage4/Stage4Player2.unity
  Assets/MasterScene/Stage5/Stage5Player1.unity
  Assets/MasterScene/Stage5/Stage5Player2.unity
  UserSettings/EditorUserSettings.asset
Labels: 機能 プログラム など :memo:, 仕様 デザイン など :art:, 未完了 :x:

#202 ボスが登場すると名前が出る
  Assets/5Adachi/Prefabs/BossEnemyPrefabs/Boss1.prefab
  Assets/5Adachi/Prefabs/BossEnemyPrefabs/Boss2.prefab
  Assets/5Adachi/Prefabs/BossEnemyPrefabs/Boss3.prefab
  Assets/5Adachi/Prefabs/BossEnemyPrefabs/Boss4.prefab
  Assets/5Adachi/Prefabs/BossEnemyPrefabs/Boss5.prefab
  Assets/5Adachi/Scenes/TestSceneAdachi.unity
Labels: 機能 プログラム など :memo:, Todo, 機能の修正 :toolbox:, 完了 :ballot_box_with_check:

#213 プレイヤー, アイテムバグ修正
  Assets/2Kanbara/InputSystem/2DShooting Late presentation.inputactions
  Assets/2Kanbara/Prefab Kanbara/Item/TestPoint.prefab
  Assets/2Kanbara/Prefab Kanbara/Player/Player1.prefab
  Assets/2Kanbara/Prefab Kanbara/Player/Player2.prefab
  Assets/2Kanbara/Prefab Kanbara/StartStageEffect/EffectText.prefab
  Assets/2Kanbara/Prefab Kanbara/StartStageEffect/Stage2EffectText.prefab
  Assets/2Kanbara/Prefab Kanbara/StartStageEffect/Stage4EffectText.prefab
  Assets/2Kanbara/Scripts Kanbara/Item/ItemBase.cs
  Assets/2Kanbara/Scripts Kanbara/Player/PlayerBase.cs
  Assets/6Kondo/Sprites/Player1ColliderSprite.png
  Assets/6Kondo/Sprites/Player1ColliderSprite.png.meta
  Assets/6Kondo/Sprites/Player2ColliderSprite.png
  Assets/6Kondo/Sprites/Player2ColliderSprite.png.meta
  Assets/MasterScene/Stage1/Stage1Player1.unity
Labels: 機能 プログラム など :memo:, 不具合修正 :wrench:, 仕様 デザイン など :art:, 機能の修正 :toolbox:, 完了 :ballot_box_with_check:

#214 ゲームマネージャー修正
  Assets/1Ito/Prefabs/===Managers===.prefab
  Assets/1Ito/Scripts Ito/Calculation/Calculator.cs
  Assets/1Ito/Scripts Ito/Manager/GameManager.cs
  Assets/1Ito/Scripts Ito/Manager/PhaseNovelManager.cs
  Assets/1Ito/Scripts Ito/Manager/SceneManager/SceneLoder.cs
  Assets/1Ito/Scripts Ito/ScriptableObject/StageParam.cs
  Assets/3Wada/Enemy/EnemyPrefab/MasterEnemy/Stage5/Stege5Phase2.prefab
  Assets/4Kojima/Scripts/TextValueChange.cs
  Assets/6Kondo/Scripts/Tutorial.cs
  UserSettings/EditorUserSettings.asset
Labels: 機能 プログラム など :memo:, 不具合発見 :bug:, 機能の修正 :toolbox:, 完了 :ballot_box_with_check:

#216 ゲームオーバー等のプレハブ修正
  Assets/4Kojima/Prefab/GameOverClear/Canvas GameClear.prefab
  Assets/4Kojima/Prefab/GameOverClear/Canvas GameOver.prefab
Labels: 仕様 デザイン など :art:

#227 サウンドマネージャー音量設定オーバロード追加
  Assets/1Ito/Scripts Ito/Manager/SoundManager.cs
Labels: 機能 プログラム など :memo:, 機能の修正 :toolbox:, 完了 :ballot_box_with_check:

#228 titorialを見やすくした
  Assets/6Kondo/Prefabs/TutorialControllerManager.prefab
  Assets/6Kondo/Prefabs/TutorialKeybordManager.prefab
  Assets/6Kondo/Scenes/TestScene.unity
  Assets/MasterScene/Tutorial/ControllerTutorialPlayer1Stage.unity
  Assets/MasterScene/Tutorial/KeybordTutorialPlayer1Stage.unity
Labels: 仕様 デザイン など :art:, 完了 :ballot_box_with_check:

#231 ステージ未解放時に表示されるUIを作成しました
  Assets/6Kondo/Prefabs/StageSelectWarningButton.prefab
  Assets/6Kondo/Prefabs/StageSelectWarningButton.prefab.meta
  Assets/6Kondo/Scenes/UITest.unity
Labels: 仕様 デザイン など :art:, 完了 :ballot_box_with_check:

#232 ステージ解放した際のUIを作成しました
  Assets/6Kondo/Prefabs/Player.meta
  Assets/6Kondo/Prefabs/Player/Bomb01Child.prefab
  Assets/6Kondo/Prefabs/Player/Bomb01Child.prefab.meta
  Assets/6Kondo/Prefabs/Player/Bomb02Child.prefab
  Assets/6Kondo/Prefabs/Player/Bomb02Child.prefab.meta
  Assets/6Kondo/Prefabs/Player/Explosion.prefab
  Assets/6Kondo/Prefabs/Player/Explosion.prefab.meta
  Assets/6Kondo/Prefabs/Player/Player01Bomb.prefab
  Assets/6Kondo/Prefabs/Player/Player01Bomb.prefab.meta
  Assets/6Kondo/Prefabs/Player/Player02Bomb.prefab
  Assets/6Kondo/Prefabs/Player/Player02Bomb.prefab.meta
  Assets/6Kondo/Prefabs/Player/Player2Effect.prefab
  Assets/6Kondo/Prefabs/Player/Player2Effect.prefab.meta
  Assets/6Kondo/Prefabs/UIPrefabs.meta
  Assets/6Kondo/Prefabs/UIPrefabs/PausePanel.prefab
  Assets/6Kondo/Prefabs/UIPrefabs/PausePanel.prefab.meta
  Assets/6Kondo/Prefabs/UIPrefabs/Stage Open Button.prefab
  Assets/6Kondo/Prefabs/UIPrefabs/Stage Open Button.prefab.meta
  Assets/6Kondo/Prefabs/UIPrefabs/StageSelectWarningButton.prefab
  Assets/6Kondo/Prefabs/UIPrefabs/StageSelectWarningButton.prefab.meta
  Assets/6Kondo/Prefabs/UIPrefabs/TutorialControllerManager.prefab
  Assets/6Kondo/Prefabs/UIPrefabs/TutorialControllerManager.prefab.meta
  Assets/6Kondo/Prefabs/UIPrefabs/TutorialKeybordManager.prefab
  Assets/6Kondo/Prefabs/UIPrefabs/TutorialKeybordManager.prefab.meta
  Assets/6Kondo/Prefabs/UIPrefabs/UIManager.prefab
  Assets/6Kondo/Prefabs/UIPrefabs/UIManager.prefab.meta
  Assets/6Kondo/Scenes/UITest.unity
Labels: 仕様 デザイン など :art:, 完了 :ballot_box_with_check:

#233 モブ敵の調整完了
  Assets/3Wada/Enemy/EnemyPrefab/MasterEnemy/Stage1/Stage1Phase1.prefab
  Assets/3Wada/Enemy/EnemyPrefab/MasterEnemy/Stage1/Stage1Phase3.prefab
  Assets/3Wada/Enemy/EnemyPrefab/MasterEnemy/Stage2/Stage2Phase1.prefab
  Assets/3Wada/Enemy/EnemyPrefab/MasterEnemy/Stage2/Stage2Phase2.prefab
  Assets/3Wada/Enemy/EnemyPrefab/MasterEnemy/Stage2/Stage2Phase3.prefab
  Assets/3Wada/Enemy/EnemyPrefab/MasterEnemy/Stage2/Stage2Phase4.prefab
  Assets/3Wada/Enemy/EnemyPrefab/MasterEnemy/Stage4/Stage4Phase2.prefab
  Assets/3Wada/Enemy/EnemyPrefab/MasterEnemy/Stage4/Stege4Phase3.prefab
  Assets/3Wada/Scenes Wada/EnemyMove.unity
Labels: 機能 プログラム など :memo:, 機能の修正 :toolbox:, 完了 :ballot_box_with_check:
