Repository ItoSeiy/2DShooting-first-grade, pull requests merged in 2022-01, with the labels that each got.

#92 Feature/object pool
  Assets/1Ito/Prefabs.meta
  Assets/1Ito/Prefabs/GameZone.prefab
  Assets/1Ito/Prefabs/GameZone.prefab.meta
  Assets/1Ito/Prefabs/PlayerBulletManager.prefab
  Assets/1Ito/Prefabs/PlayerBulletManager.prefab.meta
  Assets/1Ito/Scenes Ito/Test Ito.unity
  Assets/1Ito/Scripts Ito/Bullet/BulletBese.cs
  Assets/1Ito/Scripts Ito/Bullet/BulletPool.cs
  Assets/1Ito/Scripts Ito/Bullet/BulletSettings.cs
  Assets/1Ito/Scripts Ito/Bullet/PlayerBulletPool.cs
  Assets/1Ito/Scripts Ito/Bullet/PlayerBulletPool.cs.meta
  Assets/1Ito/Scripts Ito/Manager.meta
  Assets/1Ito/Scripts Ito/Manager/GameManager.cs
  Assets/1Ito/Scripts Ito/Manager/GameManager.cs.meta
  Assets/1Ito/Scripts Ito/TestPlayer.cs
  Assets/1Ito/Scripts Ito/TestPlayer.cs.meta
  Assets/5Adachi/Prefab/Player01BulletStraightPrefabs/Player01Power01StraightBullet.prefab
  Assets/5Adachi/Prefab/Player01BulletStraightPrefabs/Player01Power02StraightBullet.prefab
  Assets/5Adachi/Prefab/Player01BulletStraightPrefabs/Player01Power03StraightBullet.prefab
  Assets/5Adachi/Prefab/Player02BulletFollow/Player02Power01FollowBullet.prefab
  Assets/5Adachi/Prefab/Player02BulletFollow/Player02Power02FollowBullet.prefab
  Assets/5Adachi/Prefab/Player02BulletFollow/Player02Power03FollowBullet.prefab
  Assets/5Adachi/Scenes/TestSceneAdachi.unity
  Assets/5Adachi/Scripts/BulletScripts/BulletParent.cs
  Assets/5Adachi/Scripts/BulletScripts/BulletParent.cs.meta
  Assets/5Adachi/Scripts/BulletScripts/PlayerBulletFollow.cs
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/Physics2DSettings.asset
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/TagManager.asset
  UserSettings/EditorUserSettings.asset
Labels: 機能 プログラム など :memo:, 完了 :ballot_box_with_check:

#93 モブ敵の派生クラスの修正
  Assets/1Ito/Scripts Ito/Enemy/EnemyBese.cs
  Assets/3Wada/Scenes Wada/Enemy Scene.unity
  Assets/3Wada/Scenes Wada/Enemy Scene.unity.meta
  Assets/3Wada/Scripts Wada/EnemyController.cs
  Assets/3Wada/Scripts Wada/EnemyController.cs.meta
  Assets/3Wada/Scripts Wada/EnemyGenerator.cs
  Assets/3Wada/Scripts Wada/EnemyGenerator.cs.meta
  Assets/3Wada/Sprites/EnemyBulletSprites/Enemy_RedBullet.png.meta
  Assets/3Wada/wadaprefab.meta
  Assets/3Wada/wadaprefab/boll.prefab
  Assets/3Wada/wadaprefab/boll.prefab.meta
Labels: 機能 プログラム など :memo:, Todo

#95 Enemyのプール修正
  Assets/1Ito/Prefabs/EnemyManager.prefab
  Assets/1Ito/Prefabs/EnemyManager.prefab.meta
  Assets/1Ito/Scenes Ito/Test Ito.unity
  Assets/1Ito/Scripts Ito/Bullet/BulletParent.cs
  Assets/1Ito/Scripts Ito/Bullet/BulletParent.cs.meta
  Assets/1Ito/Scripts Ito/Bullet/PlayerBullet.meta
  Assets/1Ito/Scripts Ito/Bullet/PlayerBullet/BulletBese.cs
  Assets/1Ito/Scripts Ito/Bullet/PlayerBullet/BulletBese.cs.meta
  Assets/1Ito/Scripts Ito/Bullet/PlayerBullet/PlayerBulletPool.cs
  Assets/1Ito/Scripts Ito/Bullet/PlayerBullet/PlayerBulletPool.cs.meta
  Assets/1Ito/Scripts Ito/Bullet/PlayerBullet/TestBullet01.cs
  Assets/1Ito/Scripts Ito/Bullet/PlayerBullet/TestBullet01.cs.meta
  Assets/1Ito/Scripts Ito/Bullet/PlayerBullet/TestBullet02.cs
  Assets/1Ito/Scripts Ito/Bullet/PlayerBullet/TestBullet02.cs.meta
  Assets/1Ito/Scripts Ito/Enemy/EnemyPool.cs
  Assets/1Ito/Scripts Ito/Enemy/EnemyPool.cs.meta
  Assets/1Ito/Scripts Ito/Interface/IDamage.cs
Labels: 機能 プログラム など :memo:, 完了 :ballot_box_with_check:

#98 敵の弾のプール完成
  Assets/1Ito/Prefabs/EnemyBulletManager.prefab
  Assets/1Ito/Prefabs/EnemyBulletManager.prefab.meta
  Assets/1Ito/Scenes Ito/Test Ito.unity
  Assets/1Ito/Scripts Ito/Bullet/BulletBese.cs
  Assets/1Ito/Scripts Ito/Bullet/BulletBese.cs.meta
  Assets/1Ito/Scripts Ito/ObjectPool.meta
  Assets/1Ito/Scripts Ito/ObjectPool/BulletParent.cs
  Assets/1Ito/Scripts Ito/ObjectPool/BulletParent.cs.meta
  Assets/1Ito/Scripts Ito/ObjectPool/EnemyBulletPool.cs
  Assets/1Ito/Scripts Ito/ObjectPool/EnemyBulletPool.cs.meta
  Assets/1Ito/Scripts Ito/ObjectPool/EnemyPool.cs
  Assets/1Ito/Scripts Ito/ObjectPool/EnemyPool.cs.meta
  Assets/1Ito/Scripts Ito/ObjectPool/PlayerBulletPool.cs
  Assets/1Ito/Scripts Ito/ObjectPool/PlayerBulletPool.cs.meta
  Assets/1Ito/Scripts Ito/TestPlayer.cs
Labels: 機能 プログラム など :memo:, 機能の修正 :toolbox:, 完了 :ballot_box_with_check:

#99 プレイヤーのボム完成
  Assets/1Ito/Scripts Ito/Bullet/BulletBese.cs
  Assets/1Ito/Scripts Ito/Enemy/EnemyBese.cs
  Assets/1Ito/Scripts Ito/Enemy/TestEnemy01.cs
  Assets/3Wada/Sprites/ItemSprites/Bomb.png.meta
  Assets/6Kondo/Plefabs/Star.prefab
  Assets/6Kondo/Scenes/KondoTest.unity
  Assets/6Kondo/Scripts/Bomb/BombChildBullet.cs
  Assets/6Kondo/Scripts/Player01Bomb.cs
Labels: 機能 プログラム など :memo:, 完了 :ballot_box_with_check:

#101 Player01Bombの製作完了
  Assets/6Kondo/Animation.meta
  Assets/6Kondo/Animation/Bomb.controller
  Assets/6Kondo/Animation/Bomb.controller.meta
  Assets/6Kondo/Animation/BombHit.anim
  Assets/6Kondo/Animation/BombHit.anim.meta
  Assets/6Kondo/Prefabs/Player1Bomb.prefab
  Assets/6Kondo/Scenes/KondoTest.unity
  Assets/6Kondo/Scripts/Player01Bomb.cs
Labels: 機能 プログラム など :memo:, 完了 :ballot_box_with_check:

#106 オブジェクトプール修正
  Assets/1Ito/Prefabs/EnemyManager.prefab
  Assets/1Ito/Prefabs/ObjectPool.prefab
  Assets/1Ito/Prefabs/ObjectPool.prefab.meta
  Assets/1Ito/Prefabs/PlayerBulletManager.prefab
  Assets/1Ito/Scenes Ito/Test Ito.unity
  Assets/1Ito/Scripts Ito/Manager/PhaseManager.cs
  Assets/1Ito/Scripts Ito/Manager/PhaseManager.cs.meta
  Assets/1Ito/Scripts Ito/ObjectPool/EnemyBulletPool.cs
  Assets/1Ito/Scripts Ito/ObjectPool/EnemyPool.cs
  Assets/1Ito/Scripts Ito/ObjectPool/PlayerBulletPool.cs
  Assets/1Ito/Scripts Ito/ScriptableObject.meta
  Assets/1Ito/Scripts Ito/ScriptableObject/PoolObjectParam.asset
  Assets/1Ito/Scripts Ito/ScriptableObject/PoolObjectParam.asset.meta
  Assets/1Ito/Scripts Ito/ScriptableObject/PoolObjectParamAsset.cs
  Assets/1Ito/Scripts Ito/ScriptableObject/PoolObjectParamAsset.cs.meta
  Assets/1Ito/Scripts Ito/ScriptableObject/StageParam.asset
  Assets/1Ito/Scripts Ito/ScriptableObject/StageParam.asset.meta
  Assets/1Ito/Scripts Ito/ScriptableObject/StageParamAsset.cs
  Assets/1Ito/Scripts Ito/ScriptableObject/StageParamAsset.cs.meta
  Assets/MasterScene.meta
  Assets/MasterScene/SampleScene.unity
  Assets/MasterScene/SampleScene.unity.meta
Labels: 機能 プログラム など :memo:, 機能の修正 :toolbox:

#107 音を出力する機能を追加した
  Assets/1Ito/Scripts Ito/Manager/GameManager.cs
  Assets/2Kanbara/Audio.meta
  Assets/2Kanbara/Audio/AudioCharge.wav
  Assets/2Kanbara/Audio/AudioCharge.wav.meta
  Assets/2Kanbara/Audio/ChargeShot.wav
  Assets/2Kanbara/Audio/ChargeShot.wav.meta
  Assets/2Kanbara/InputSystem/2DShooting Late presentation.inputactions
  Assets/2Kanbara/Prefab Kanbara/PlayerDestroyAudio.prefab
  Assets/2Kanbara/Prefab Kanbara/PlayerDestroyAudio.prefab.meta
  Assets/2Kanbara/Scenes Kanbara/Prayer movement.unity
  Assets/2Kanbara/Scripts Kanbara/Audio.meta
  Assets/2Kanbara/Scripts Kanbara/Audio/AudioData.cs
  Assets/2Kanbara/Scripts Kanbara/Audio/AudioData.cs.meta
  Assets/2Kanbara/Scripts Kanbara/Audio/PlayerDestroyAudioScript.cs
  Assets/2Kanbara/Scripts Kanbara/Audio/PlayerDestroyAudioScript.cs.meta
  Assets/2Kanbara/Scripts Kanbara/Player/Player1.cs
  Assets/2Kanbara/Scripts Kanbara/Player/Player2.cs
  Assets/2Kanbara/Scripts Kanbara/Player/PlayerBase.cs
Labels: 機能 プログラム など :memo:, 不具合修正 :wrench:, 機能の修正 :toolbox:, 未完了 :x:
