Repository ItoSeiy/2DShooting-first-grade, pull requests merged in 2022-02, with the labels that each got.

#108 自機実装中
  Assets/2Kanbara/Audio/AudioClip.meta
  Assets/2Kanbara/Audio/AudioClip/AudioCharge.wav
  Assets/2Kanbara/Audio/AudioClip/AudioCharge.wav.meta
  Assets/2Kanbara/Audio/AudioClip/ChargeShot.wav
  Assets/2Kanbara/Audio/AudioClip/ChargeShot.wav.meta
  Assets/2Kanbara/Audio/AudioMixer.meta
  Assets/2Kanbara/Audio/AudioMixer/AudioMixer.mixer
  Assets/2Kanbara/Audio/AudioMixer/AudioMixer.mixer.meta
  Assets/2Kanbara/InputSystem/2DShooting Late presentation.inputactions
  Assets/2Kanbara/Scenes Kanbara/Prayer movement.unity
  Assets/2Kanbara/Scripts Kanbara/Player/PlayerBase.cs
Labels: 機能 プログラム など :memo:, 不具合修正 :wrench:, 機能の修正 :toolbox:, 未完了 :x:

#109 ボムのバグ修正
  Assets/1Ito/Scripts Ito/Manager/GameManager.cs
  Assets/2Kanbara/InputSystem/2DShooting Late presentation.inputactions
  Assets/2Kanbara/Prefab Kanbara/PlayerBullet/Player01/Player01BulletStraightPrefabs/Player01Power01StraightBullet.prefab
  Assets/2Kanbara/Prefab Kanbara/PlayerBullet/Player01/Player01BulletStraightPrefabs/Player01Power02StraightBullet.prefab
  Assets/2Kanbara/Prefab Kanbara/PlayerBullet/Player01/Player01BulletStraightPrefabs/Player01Power03StraightBullet.prefab
  Assets/2Kanbara/Prefab Kanbara/PlayerBullet/Player01/Player01ChargeShotPrefabs/Player01Power01ChargeShot.prefab
  Assets/2Kanbara/Prefab Kanbara/PlayerBullet/Player01/Player01ChargeShotPrefabs/Player01Power02ChargeShot.prefab
  Assets/2Kanbara/Prefab Kanbara/PlayerBullet/Player01/Player01ChargeShotPrefabs/Player01Power03ChargeShot.prefab
  Assets/2Kanbara/Prefab Kanbara/PlayerBullet/Player01/Player01SuperAttackPrefabs/Player01Power01SuperAttack.prefab
  Assets/2Kanbara/Prefab Kanbara/PlayerBullet/Player01/Player01SuperAttackPrefabs/Player01Power02SuperAttack.prefab
  Assets/2Kanbara/Prefab Kanbara/PlayerBullet/Player01/Player01SuperAttackPrefabs/Player01Power03SuperAttack.prefab
  Assets/2Kanbara/Prefab Kanbara/PlayerBullet/Player02/Player02BulletFollow/Player02Power01FollowBullet.prefab
  Assets/2Kanbara/Prefab Kanbara/PlayerBullet/Player02/Player02BulletFollow/Player02Power02FollowBullet.prefab
  Assets/2Kanbara/Prefab Kanbara/PlayerBullet/Player02/Player02BulletFollow/Player02Power03FollowBullet.prefab
  Assets/2Kanbara/Prefab Kanbara/PlayerBullet/Player02/Player02ChargeShotPrefabs/Player02Power01ChargeShot.prefab
  Assets/2Kanbara/Prefab Kanbara/PlayerBullet/Player02/Player02ChargeShotPrefabs/Player02Power02ChargeShot.prefab
  Assets/2Kanbara/Prefab Kanbara/PlayerBullet/Player02/Player02ChargeShotPrefabs/Player02Power03ChargeShot.prefab
  Assets/2Kanbara/Prefab Kanbara/PlayerBullet/Player02/Player02SuperAttackPrefabs/Player02Power01SuperAttack.prefab
  Assets/2Kanbara/Prefab Kanbara/PlayerBullet/Player02/Player02SuperAttackPrefabs/Player02Power02SuperAttack.prefab
  Assets/2Kanbara/Prefab Kanbara/PlayerBullet/Player02/Player02SuperAttackPrefabs/Player02Power03SuperAttack.prefab
  Assets/2Kanbara/Scenes Kanbara/PlayerMovement.unity
  Assets/2Kanbara/Scenes Kanbara/PlayerMovement.unity.meta
  Assets/2Kanbara/Scripts Kanbara/Item/ItemBase.cs
  Assets/2Kanbara/Scripts Kanbara/Player/Player1.cs
  Assets/2Kanbara/Scripts Kanbara/Player/Player2.cs
  Assets/2Kanbara/Scripts Kanbara/Player/PlayerBase.cs
  Assets/6Kondo/Prefabs/Bomb01Child.prefab
Labels: 機能 プログラム など :memo:, 不具合修正 :wrench:, 機能の修正 :toolbox:, 未完了 :x:

#111 Feature/title
  Assets/4Kojima/Animation.meta
  Assets/4Kojima/Animation/Image.meta
  Assets/4Kojima/Animation/Image/Image 1.controller
  Assets/4Kojima/Animation/Image/Image 1.controller.meta
  Assets/4Kojima/Animation/Image/Image B Animation.anim
  Assets/4Kojima/Animation/Image/Image B Animation.anim.meta
  Assets/4Kojima/Animation/Image/Image G Animation.anim
  Assets/4Kojima/Animation/Image/Image G Animation.anim.meta
  Assets/4Kojima/Animation/Image/Image.controller
  Assets/4Kojima/Animation/Image/Image.controller.meta
  Assets/4Kojima/Animation/background.controller
  Assets/4Kojima/Animation/background.controller.meta
  Assets/4Kojima/Animation/background1.controller
  Assets/4Kojima/Animation/background1.controller.meta
  Assets/4Kojima/Animation/background2.controller
  Assets/4Kojima/Animation/background2.controller.meta
  Assets/4Kojima/Animation/background3.controller
  Assets/4Kojima/Animation/background3.controller.meta
  Assets/4Kojima/Animation/background4.controller
  Assets/4Kojima/Animation/background4.controller.meta
  Assets/4Kojima/Object/Cube R.mat
  Assets/4Kojima/Object/Cube.prefab
  Assets/4Kojima/Object/New Material.mat
  Assets/4Kojima/Object/New Material.mat.meta
  Assets/4Kojima/Object/TitleMaterial.mat
  Assets/4Kojima/Object/TitleMaterial.mat.meta
  Assets/4Kojima/Scenes Kojima/Title_Kojima.unity
  Assets/4Kojima/Sounde.meta
  Assets/4Kojima/Sounde/Crick SE.mp3
  Assets/4Kojima/Sounde/Crick SE.mp3.meta
  Assets/4Kojima/Sprite/BackGround.png
  Assets/4Kojima/Sprite/BackGround.png.meta
  Assets/4Kojima/Sprite/Close.png
  Assets/4Kojima/Sprite/Close.png.meta
  Assets/4Kojima/Sprite/Difficulty setting.png
  Assets/4Kojima/Sprite/Difficulty setting.png.meta
  Assets/4Kojima/Sprite/Operation settings.png
  Assets/4Kojima/Sprite/Operation settings.png.meta
  Assets/4Kojima/Sprite/background1.png.meta
  Assets/4Kojima/Sprite/background2.png.meta
  Assets/4Kojima/Sprite/background3.png.meta
  Assets/4Kojima/Sprite/background4.png.meta
  Assets/4Kojima/Sprite/flame.png
  Assets/4Kojima/Sprite/flame.png.meta
  Assets/4Kojima/Timeline.meta
  Assets/4Kojima/Timeline/Title.playable
  Assets/4Kojima/Timeline/Title.playable.meta
  Assets/4Kojima/timeline.meta
  Assets/4Kojima/timeline/BackgroundTimeline.playable
  Assets/4Kojima/timeline/BackgroundTimeline.playable.meta
  Assets/4Kojima/timeline/Close ButtonTimeline.playable
  Assets/4Kojima/timeline/Close ButtonTimeline.playable.meta
  Assets/4Kojima/timeline/Operation settings ButtonTimeline.playable
  Assets/4Kojima/timeline/Operation settings ButtonTimeline.playable.meta
  Assets/4Kojima/timeline/Panel change.playable
  Assets/4Kojima/timeline/Panel change.playable.meta
  Assets/4Kojima/timeline/TitleLogoJTimeline.playable
  Assets/4Kojima/timeline/TitleLogoJTimeline.playable.meta
  ProjectSettings/TimelineSettings.asset
Labels: 機能 プログラム など :memo:, 仕様 デザイン など :art:, 未完了 :x:

#114 自機の機能がほぼ完成
  Assets/1Ito/Scripts Ito/Manager/GameManager.cs
  Assets/1Ito/Scripts Ito/ScriptableObject/PoolObjectParam.asset
  Assets/2Kanbara/Animation.meta
  Assets/2Kanbara/Animation/Player1AnimationClip.meta
  Assets/2Kanbara/Animation/Player1AnimationClip/Player1AttackClip.anim
  Assets/2Kanbara/Animation/Player1AnimationClip/Player1AttackClip.anim.meta
  Assets/2Kanbara/Animation/Player1AnimationClip/Player1InvicibleClip.anim
  Assets/2Kanbara/Animation/Player1AnimationClip/Player1InvicibleClip.anim.meta
  Assets/2Kanbara/Animation/Player1AnimationContller.meta
  Assets/2Kanbara/Animation/Player1AnimationContller/Player1.controller
  Assets/2Kanbara/Animation/Player1AnimationContller/Player1.controller.meta
  Assets/2Kanbara/Animation/Player2AnimationClip.meta
  Assets/2Kanbara/Animation/Player2AnimationClip/Player2AttackClip.anim
  Assets/2Kanbara/Animation/Player2AnimationClip/Player2AttackClip.anim.meta
  Assets/2Kanbara/Animation/Player2AnimationClip/Player2InvicibleClip.anim
  Assets/2Kanbara/Animation/Player2AnimationClip/Player2InvicibleClip.anim.meta
  Assets/2Kanbara/Animation/Player2AnimationContller.meta
  Assets/2Kanbara/Animation/Player2AnimationContller/Player2.controller
  Assets/2Kanbara/Animation/Player2AnimationContller/Player2.controller.meta
  Assets/2Kanbara/InputSystem/2DShooting Late presentation.inputactions
  Assets/2Kanbara/ParticalSystem.meta
  Assets/2Kanbara/ParticalSystem/Player1ChargeAttackParticleSystem.prefab
  Assets/2Kanbara/ParticalSystem/Player1ChargeAttackParticleSystem.prefab.meta
  Assets/2Kanbara/Prefab Kanbara/Muzzle.prefab
  Assets/2Kanbara/Prefab Kanbara/PlayerBullet/Player01/Player01BulletStraightPrefabs/Player01Power01StraightBullet.prefab
  Assets/2Kanbara/Prefab Kanbara/PlayerBullet/Player01/Player01BulletStraightPrefabs/Player01Power02StraightBullet.prefab
  Assets/2Kanbara/Prefab Kanbara/PlayerBullet/Player01/Player01BulletStraightPrefabs/Player01Power03StraightBullet.prefab
  Assets/2Kanbara/Prefab Kanbara/PlayerBullet/Player01/Player01ChargeShotPrefabs/Player01Power01ChargeShot.prefab
  Assets/2Kanbara/Prefab Kanbara/PlayerBullet/Player01/Player01ChargeShotPrefabs/Player01Power02ChargeShot.prefab
  Assets/2Kanbara/Prefab Kanbara/PlayerBullet/Player01/Player01ChargeShotPrefabs/Player01Power03ChargeShot.prefab
  Assets/2Kanbara/Prefab Kanbara/PlayerBullet/Player01/Player01SuperAttackPrefabs/Player01Power01SuperAttack.prefab
  Assets/2Kanbara/Prefab Kanbara/PlayerBullet/Player01/Player01SuperAttackPrefabs/Player01Power02SuperAttack.prefab
  Assets/2Kanbara/Prefab Kanbara/PlayerBullet/Player01/Player01SuperAttackPrefabs/Player01Power03SuperAttack.prefab
  Assets/2Kanbara/Prefab Kanbara/PlayerBullet/Player02/Player02BulletFollow/Player02Power01FollowBullet.prefab
  Assets/2Kanbara/Prefab Kanbara/PlayerBullet/Player02/Player02BulletFollow/Player02Power02FollowBullet.prefab
  Assets/2Kanbara/Prefab Kanbara/PlayerBullet/Player02/Player02BulletFollow/Player02Power03FollowBullet.prefab
  Assets/2Kanbara/Prefab Kanbara/PlayerBullet/Player02/Player02ChargeShotPrefabs/Player02Power01ChargeShot.prefab
  Assets/2Kanbara/Prefab Kanbara/PlayerBullet/Player02/Player02ChargeShotPrefabs/Player02Power02ChargeShot.prefab
  Assets/2Kanbara/Prefab Kanbara/PlayerBullet/Player02/Player02ChargeShotPrefabs/Player02Power03ChargeShot.prefab
  Assets/2Kanbara/Prefab Kanbara/PlayerBullet/Player02/Player02SuperAttackPrefabs/Player02Power01SuperAttack.prefab
  Assets/2Kanbara/Prefab Kanbara/PlayerBullet/Player02/Player02SuperAttackPrefabs/Player02Power02SuperAttack.prefab
  Assets/2Kanbara/Prefab Kanbara/PlayerBullet/Player02/Player02SuperAttackPrefabs/Player02Power03SuperAttack.prefab
  Assets/2Kanbara/Scenes Kanbara/PlayerMovement.unity
  Assets/2Kanbara/Scripts Kanbara/Player/Player1.cs
  Assets/2Kanbara/Scripts Kanbara/Player/Player2.cs
  Assets/2Kanbara/Scripts Kanbara/Player/PlayerBase.cs
  Assets/6Kondo/Scripts/Bomb/Player01Bomb.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: 機能 プログラム など :memo:, 不具合修正 :wrench:, 機能の修正 :toolbox:, 未完了 :x:

#118 モブ敵引継ぎ
  Assets/1Ito/EnemyTakeOver.meta
  Assets/1Ito/EnemyTakeOver/EnemyPrefab.meta
  Assets/1Ito/EnemyTakeOver/EnemyPrefab/DownEnemy.prefab
  Assets/1Ito/EnemyTakeOver/EnemyPrefab/DownEnemy.prefab.meta
  Assets/1Ito/EnemyTakeOver/EnemyPrefab/LeftEnemy .prefab
  Assets/1Ito/EnemyTakeOver/EnemyPrefab/LeftEnemy .prefab.meta
  Assets/1Ito/EnemyTakeOver/EnemyPrefab/RightEnemy  .prefab
  Assets/1Ito/EnemyTakeOver/EnemyPrefab/RightEnemy  .prefab.meta
  Assets/1Ito/EnemyTakeOver/EnemyPrefab/UpEnemy    1.prefab
  Assets/1Ito/EnemyTakeOver/EnemyPrefab/UpEnemy    1.prefab.meta
  Assets/1Ito/EnemyTakeOver/EnemyScripts.meta
  Assets/1Ito/EnemyTakeOver/EnemyScripts/Audio.cs
  Assets/1Ito/EnemyTakeOver/EnemyScripts/Audio.cs.meta
  Assets/1Ito/EnemyTakeOver/EnemyScripts/EnemyBullt.cs
  Assets/1Ito/EnemyTakeOver/EnemyScripts/EnemyBullt.cs.meta
  Assets/1Ito/EnemyTakeOver/EnemyScripts/EnemyController.cs
  Assets/1Ito/EnemyTakeOver/EnemyScripts/EnemyController.cs.meta
  Assets/3Wada/Scenes Wada/Enemy Scene.unity
  Assets/3Wada/Scripts Wada/EnemyGenerator.cs
  Assets/3Wada/Scripts Wada/Test Wada.cs
  Assets/3Wada/wadaprefab/boll.prefab
Labels: 機能 プログラム など :memo:, 未完了 :x:

#122 変数名を変更
  Assets/2Kanbara/Animation/Player1AnimationContller/Player1.controller
  Assets/2Kanbara/Animation/Player2AnimationContller/Player2.controller
  Assets/2Kanbara/ParticalSystem/1UPItemParticleSystem.prefab
  Assets/2Kanbara/ParticalSystem/1UPItemParticleSystem.prefab.meta
  Assets/2Kanbara/ParticalSystem/FullPowerParticleSystem.prefab
  Assets/2Kanbara/ParticalSystem/FullPowerParticleSystem.prefab.meta
  Assets/2Kanbara/ParticalSystem/PowerItemParticleSystem.prefab
  Assets/2Kanbara/ParticalSystem/PowerItemParticleSystem.prefab.meta
  Assets/2Kanbara/ParticalSystem/SuperModeEffectB.prefab
  Assets/2Kanbara/ParticalSystem/SuperModeEffectB.prefab.meta
  Assets/2Kanbara/ParticalSystem/SuperModeEffectG.prefab
  Assets/2Kanbara/ParticalSystem/SuperModeEffectG.prefab.meta
  Assets/2Kanbara/ParticalSystem/SuperModeEffectR.prefab
  Assets/2Kanbara/ParticalSystem/SuperModeEffectR.prefab.meta
  Assets/2Kanbara/Prefab Kanbara/PlayerBullet/Player01/Player01ChargeShotPrefabs/Player01Power01ChargeShot.prefab
  Assets/2Kanbara/Scenes Kanbara/PlayerMovement.unity
  Assets/2Kanbara/Scripts Kanbara/Player/PlayerBase.cs
  Assets/2Kanbara/Scripts Kanbara/Player/SuperModeEffect.cs
  Assets/2Kanbara/Scripts Kanbara/Player/SuperModeEffect.cs.meta
Labels: 機能 プログラム など :memo:, 不具合修正 :wrench:, 機能の修正 :toolbox:, 完了 :ballot_box_with_check:

#123 アイテム回収機能WIP
  Assets/2Kanbara/Prefab Kanbara/Player1TriggerColider.prefab
  Assets/2Kanbara/Prefab Kanbara/Player1TriggerColider.prefab.meta
  Assets/2Kanbara/Prefab Kanbara/Player2TriggerColider.prefab
  Assets/2Kanbara/Prefab Kanbara/Player2TriggerColider.prefab.meta
  Assets/2Kanbara/Prefab Kanbara/PlayerBullet/Player02/Player02BulletFollow/Player02Power02FollowBullet.prefab
  Assets/2Kanbara/Scenes Kanbara/PlayerMovement.unity
  Assets/2Kanbara/Scripts Kanbara/Item/ItemBase.cs
  Assets/2Kanbara/Scripts Kanbara/Item/ItemGetLine.cs
  Assets/2Kanbara/Scripts Kanbara/Item/ItemGetLine.cs.meta
  Assets/2Kanbara/Scripts Kanbara/Player/PlayerBase.cs
Labels: 機能 プログラム など :memo:, 不具合修正 :wrench:, 機能の修正 :toolbox:, 未完了 :x:

#124 floatをintにした
  Assets/2Kanbara/Scripts Kanbara/Player/PlayerBase.cs
Labels: 機能 プログラム など :memo:, 不具合修正 :wrench:, 機能の修正 :toolbox:

#125 プロパティを追加
  Assets/1Ito/Scripts Ito/Manager/GameManager.cs
  Assets/2Kanbara/Scenes Kanbara/PlayerMovement.unity
  Assets/2Kanbara/Scripts Kanbara/Item/ItemBase.cs
  Assets/2Kanbara/Scripts Kanbara/Item/ItemGetLine.cs
  Assets/2Kanbara/Scripts Kanbara/Player/PlayerBase.cs
Labels: 機能 プログラム など :memo:, 不具合修正 :wrench:, 機能の修正 :toolbox:, 未完了 :x:

#126 アイテム回収機能を追加
  Assets/2Kanbara/Player.meta
  Assets/2Kanbara/Player/Player1.prefab
  Assets/2Kanbara/Player/Player1.prefab.meta
  Assets/2Kanbara/Player/Player2.prefab
  Assets/2Kanbara/Player/Player2.prefab.meta
  Assets/2Kanbara/Prefab Kanbara/ItemGetLineCollider.prefab
  Assets/2Kanbara/Prefab Kanbara/ItemGetLineCollider.prefab.meta
  Assets/2Kanbara/Prefab Kanbara/Test1UP.prefab
  Assets/2Kanbara/Prefab Kanbara/TestBomItem.prefab
  Assets/2Kanbara/Prefab Kanbara/TestPoint.prefab
  Assets/2Kanbara/Prefab Kanbara/TestPower.prefab
  Assets/2Kanbara/Scenes Kanbara/PlayerMovement.unity
  Assets/2Kanbara/Scripts Kanbara/Item/ItemBase.cs
  Assets/2Kanbara/Scripts Kanbara/Item/ItemGetLine.cs
  Assets/2Kanbara/Scripts Kanbara/Item/ItemGetLine.cs.meta
  Assets/2Kanbara/Scripts Kanbara/Player/PlayerBase.cs
Labels: 機能 プログラム など :memo:, 不具合修正 :wrench:, 機能の修正 :toolbox:, 完了 :ballot_box_with_check:

#129 ボスの動き完成
  Assets/3Wada/Sprites/EnemyBulletSprites/Boss5defaultBulet.png.meta
  Assets/5Adachi/Scenes/TestSceneAdachi.unity
  Assets/5Adachi/Scripts/BossEnemyMoveCircle.cs
  Assets/5Adachi/Scripts/BossEnemyMoveCircle.cs.meta
  Assets/5Adachi/Scripts/BossEnemyMovementScripts.meta
  Assets/5Adachi/Scripts/BossEnemyMovementScripts/BossEnemyMovement01.cs
  Assets/5Adachi/Scripts/BossEnemyMovementScripts/BossEnemyMovement01.cs.meta
  Assets/5Adachi/Scripts/BossEnemyMovementScripts/BossEnemyMovement02.cs
  Assets/5Adachi/Scripts/BossEnemyMovementScripts/BossEnemyMovement02.cs.meta
  Assets/5Adachi/Scripts/BossEnemyMovementScripts/BossEnemyMovement03.cs
  Assets/5Adachi/Scripts/BossEnemyMovementScripts/BossEnemyMovement03.cs.meta
  Assets/5Adachi/Scripts/BossEnemyMovementScripts/BossEnemyMovement04.cs
  Assets/5Adachi/Scripts/BossEnemyMovementScripts/BossEnemyMovement04.cs.meta
  Assets/5Adachi/Scripts/BossEnemyMovementScripts/BossEnemyMovement05.cs
  Assets/5Adachi/Scripts/BossEnemyMovementScripts/BossEnemyMovement05.cs.meta
  Assets/5Adachi/Scripts/BossSpecialAttack.meta
  Assets/5Adachi/Scripts/BossSpecialAttack/TestSpecialAttack.cs
  Assets/5Adachi/Scripts/BossSpecialAttack/TestSpecialAttack.cs.meta
  Assets/5Adachi/Scripts/MovementScripts.meta
  Assets/5Adachi/Scripts/MovementScripts/BossEnemyMoveRandom.cs
  Assets/5Adachi/Scripts/MovementScripts/BossEnemyMoveRandom.cs.meta
  Assets/5Adachi/Scripts/MovementScripts/BossEnemyMoveRush.cs
  Assets/5Adachi/Scripts/MovementScripts/BossEnemyMoveRush.cs.meta
  Assets/5Adachi/Scripts/MovementScripts/BossEnemyMoveThunder.cs
  Assets/5Adachi/Scripts/MovementScripts/BossEnemyMoveThunder.cs.meta
  Assets/5Adachi/Scripts/MovementScripts/BossEnemyMoveUShaped.cs
  Assets/5Adachi/Scripts/MovementScripts/BossEnemyMoveUShaped.cs.meta
  Assets/5Adachi/Scripts/PlayerBulletFollow.cs
  Assets/5Adachi/Scripts/PlayerBulletFollow.cs.meta
  Assets/5Adachi/Scripts/PlayerBulletStraight.cs
  Assets/5Adachi/Scripts/PlayerBulletStraight.cs.meta
  Assets/5Adachi/Square.prefab
  Assets/5Adachi/Square.prefab.meta
  Assets/5Adachi/TestMove.cs
  Assets/5Adachi/TestMove.cs.meta
  Assets/5Adachi/Timeline.meta
  Assets/5Adachi/Timeline/Boss01Timeline.playable
  Assets/5Adachi/Timeline/Boss01Timeline.playable.meta
  Assets/5Adachi/Timeline/Boss02Timeline.playable
  Assets/5Adachi/Timeline/Boss02Timeline.playable.meta
  Assets/5Adachi/Timeline/Boss03Timeline.playable
  Assets/5Adachi/Timeline/Boss03Timeline.playable.meta
  Assets/5Adachi/Timeline/Boss04Timeline.playable
  Assets/5Adachi/Timeline/Boss04Timeline.playable.meta
  Assets/5Adachi/Timeline/Boss05Timeline.playable
  Assets/5Adachi/Timeline/Boss05Timeline.playable.meta
  Assets/5Adachi/Timeline/BossTimeline.playable
  Assets/5Adachi/Timeline/BossTimeline.playable.meta
  Assets/5Adachi/Timeline/NotDoneYet.cs
  Assets/5Adachi/Timeline/NotDoneYet.cs.meta
Labels: 機能 プログラム など :memo:, 完了 :ballot_box_with_check:, 未完了 :x:

#132 UI完成
  Assets/6Kondo/Prefabs/UICanvas.prefab
  Assets/6Kondo/Scenes/TestScene.unity
  Assets/6Kondo/Scenes/UITest.unity
  Assets/6Kondo/Scripts/UIManager.cs
Labels: 機能 プログラム など :memo:, 仕様 デザイン など :art:, 完了 :ballot_box_with_check:

#133 UIManager完成
  Assets/6Kondo/Prefabs/UIManager.prefab
  Assets/6Kondo/Prefabs/UIManager.prefab.meta
  Assets/6Kondo/Scenes/TestScene.unity
  Assets/6Kondo/Scenes/UITest.unity
Labels: 機能 プログラム など :memo:, 仕様 デザイン など :art:, 完了 :ballot_box_with_check:

#134 タイトル
  Assets/4Kojima/Scenes Kojima/Title_Kojima.unity
  Assets/4Kojima/Sounde/Click Sfx 01.mp3
  Assets/4Kojima/Sounde/Click Sfx 01.mp3.meta
  Assets/4Kojima/Sounde/Click Sfx 02.mp3
  Assets/4Kojima/Sounde/Click Sfx 02.mp3.meta
  Assets/4Kojima/Sounde/Click Sfx 03.mp3
  Assets/4Kojima/Sounde/Click Sfx 03.mp3.meta
  Assets/4Kojima/Sounde/Click Sfx 04.mp3
  Assets/4Kojima/Sounde/Click Sfx 04.mp3.meta
  Assets/4Kojima/Sounde/Click Sfx 05.mp3
  Assets/4Kojima/Sounde/Click Sfx 05.mp3.meta
  Assets/4Kojima/Sounde/Test Crick SFX.mp3
  Assets/4Kojima/Sounde/Test Crick SFX.mp3.meta
  Assets/4Kojima/timeline/Active FalseTimeline.playable
  Assets/4Kojima/timeline/Active FalseTimeline.playable.meta
  Assets/4Kojima/timeline/Anim&Button Back AnimTimeline.playable
  Assets/4Kojima/timeline/Anim&Button Back AnimTimeline.playable.meta
  Assets/4Kojima/timeline/Anim&Button ButtonTimeline.playable
  Assets/4Kojima/timeline/Anim&Button ButtonTimeline.playable.meta
  Assets/4Kojima/timeline/Anim&Button Transparency AnimTimeline.playable
  Assets/4Kojima/timeline/Anim&Button Transparency AnimTimeline.playable.meta
  Assets/4Kojima/timeline/BackgroundTimeline.playable
  Assets/4Kojima/timeline/ChangeAnimTimeline.playable
  Assets/4Kojima/timeline/ChangeAnimTimeline.playable.meta
  Assets/4Kojima/timeline/FalseAnimTimeline.playable
  Assets/4Kojima/timeline/FalseAnimTimeline.playable.meta
  Assets/4Kojima/timeline/LogoAnim - serectTimeline.playable
  Assets/4Kojima/timeline/LogoAnim - serectTimeline.playable.meta
  Assets/4Kojima/timeline/LogoAnim - title&serectTimeline.playable
  Assets/4Kojima/timeline/LogoAnim - title&serectTimeline.playable.meta
  Assets/4Kojima/timeline/LogoAnim - titleTimeline.playable
  Assets/4Kojima/timeline/PPB ButtonTimeline.playable
  Assets/4Kojima/timeline/Player Select ButtonTimeline.playable
  Assets/4Kojima/timeline/Player Select ButtonTimeline.playable.meta
  Assets/4Kojima/timeline/PlayerCelectExpositionTimeline.playable
  Assets/4Kojima/timeline/PlayerCelectExpositionTimeline.playable.meta
  Assets/4Kojima/timeline/PlayerSelect Transparency AnimTimeline.playable
  Assets/4Kojima/timeline/PlayerSelect Transparency AnimTimeline.playable.meta
  Assets/4Kojima/timeline/Stert ButtonTimeline.playable
Labels: 仕様 デザイン など :art:, 完了 :ballot_box_with_check:

#140 自機ほとんど完成
  Assets/1Ito/Scripts Ito/Manager/GameManager.cs
  Assets/2Kanbara/ParticalSystem/InvincibleModeParticleSystem.prefab
  Assets/2Kanbara/ParticalSystem/InvincibleModeParticleSystem.prefab.meta
  Assets/2Kanbara/ParticalSystem/InvisibleItemParticleSystem.prefab
  Assets/2Kanbara/ParticalSystem/InvisibleItemParticleSystem.prefab.meta
  Assets/2Kanbara/Prefab Kanbara/Item.meta
  Assets/2Kanbara/Prefab Kanbara/Item/Test1UP.prefab
  Assets/2Kanbara/Prefab Kanbara/Item/Test1UP.prefab.meta
  Assets/2Kanbara/Prefab Kanbara/Item/TestBomItem.prefab
  Assets/2Kanbara/Prefab Kanbara/Item/TestBomItem.prefab.meta
  Assets/2Kanbara/Prefab Kanbara/Item/TestInvincible.prefab
  Assets/2Kanbara/Prefab Kanbara/Item/TestInvincible.prefab.meta
  Assets/2Kanbara/Prefab Kanbara/Item/TestPoint.prefab
  Assets/2Kanbara/Prefab Kanbara/Item/TestPoint.prefab.meta
  Assets/2Kanbara/Prefab Kanbara/Item/TestPower.prefab
  Assets/2Kanbara/Prefab Kanbara/Item/TestPower.prefab.meta
  Assets/2Kanbara/Prefab Kanbara/Player.meta
  Assets/2Kanbara/Prefab Kanbara/Player/Main Camera.prefab
  Assets/2Kanbara/Prefab Kanbara/Player/Main Camera.prefab.meta
  Assets/2Kanbara/Prefab Kanbara/Player/NormalCAM.prefab
  Assets/2Kanbara/Prefab Kanbara/Player/NormalCAM.prefab.meta
  Assets/2Kanbara/Prefab Kanbara/Player/Player1.prefab
  Assets/2Kanbara/Prefab Kanbara/Player/Player1.prefab.meta
  Assets/2Kanbara/Prefab Kanbara/Player/Player2.prefab
  Assets/2Kanbara/Prefab Kanbara/Player/Player2.prefab.meta
  Assets/2Kanbara/Prefab Kanbara/Player/QuakeCAM.prefab
  Assets/2Kanbara/Prefab Kanbara/Player/QuakeCAM.prefab.meta
  Assets/2Kanbara/Scenes Kanbara/PlayerMovement.unity
  Assets/2Kanbara/Scripts Kanbara/Item/ItemBase.cs
  Assets/2Kanbara/Scripts Kanbara/Item/TestGenerator.cs
  Assets/2Kanbara/Scripts Kanbara/Item/TestGenerator.cs.meta
  Assets/2Kanbara/Scripts Kanbara/Player/Player1.cs
  Assets/2Kanbara/Scripts Kanbara/Player/Player2.cs
  Assets/2Kanbara/Scripts Kanbara/Player/PlayerBase.cs
  Assets/2Kanbara/Scripts Kanbara/Player/PlayerItemGet.cs
  Assets/2Kanbara/Scripts Kanbara/Player/PlayerItemGet.cs.meta
  Assets/6Kondo/Scripts/UIManager.cs
Labels: 機能 プログラム など :memo:, 不具合修正 :wrench:, 機能の修正 :toolbox:, 未完了 :x:

#141 ボス的必殺技完成
  Assets/5Adachi/Prefabs.meta
  Assets/5Adachi/Prefabs/BossDelayFollowBullet.prefab
  Assets/5Adachi/Prefabs/BossDelayFollowBullet.prefab.meta
  Assets/5Adachi/Prefabs/BossReboundBullet.prefab
  Assets/5Adachi/Prefabs/BossReboundBullet.prefab.meta
  Assets/5Adachi/Prefabs/BossStraightBullet.prefab
  Assets/5Adachi/Prefabs/BossStraightBullet.prefab.meta
  Assets/5Adachi/Prefabs/MuzzleToPlayer.prefab
  Assets/5Adachi/Prefabs/MuzzleToPlayer.prefab.meta
  Assets/5Adachi/Scenes/TestSceneAdachi.unity
  Assets/5Adachi/Scripts/BossEnemyBulletScripts.meta
  Assets/5Adachi/Scripts/BossEnemyBulletScripts/BossEnemyBulletDelayFollow.cs
  Assets/5Adachi/Scripts/BossEnemyBulletScripts/BossEnemyBulletDelayFollow.cs.meta
  Assets/5Adachi/Scripts/BossEnemyBulletScripts/BossEnemyBulletRebound.cs
  Assets/5Adachi/Scripts/BossEnemyBulletScripts/BossEnemyBulletRebound.cs.meta
  Assets/5Adachi/Scripts/BossEnemyBulletScripts/BossEnemyBulletStraight.cs
  Assets/5Adachi/Scripts/BossEnemyBulletScripts/BossEnemyBulletStraight.cs.meta
  Assets/5Adachi/Scripts/BossNormalAttack.meta
  Assets/5Adachi/Scripts/BossNormalAttack/BossNormalAttack01.cs
  Assets/5Adachi/Scripts/BossNormalAttack/BossNormalAttack01.cs.meta
  Assets/5Adachi/Scripts/BossNormalAttack/BossNormalAttack02.cs
  Assets/5Adachi/Scripts/BossNormalAttack/BossNormalAttack02.cs.meta
  Assets/5Adachi/Scripts/BossNormalAttack/BossNormalAttack03.cs
  Assets/5Adachi/Scripts/BossNormalAttack/BossNormalAttack03.cs.meta
  Assets/5Adachi/Scripts/BossNormalAttack/BossNormalAttack04.cs
  Assets/5Adachi/Scripts/BossNormalAttack/BossNormalAttack04.cs.meta
  Assets/5Adachi/Scripts/BossSuperAttack.meta
  Assets/5Adachi/Scripts/BossSuperAttack/SuperAttackDelayFollow.cs
  Assets/5Adachi/Scripts/BossSuperAttack/SuperAttackDelayFollow.cs.meta
  Assets/5Adachi/Scripts/BossSuperAttack/SuperAttackEightShape.cs
  Assets/5Adachi/Scripts/BossSuperAttack/SuperAttackEightShape.cs.meta
  Assets/5Adachi/Scripts/BossSuperAttack/SuperAttackFirework.cs
  Assets/5Adachi/Scripts/BossSuperAttack/SuperAttackFirework.cs.meta
  Assets/5Adachi/Scripts/BossSuperAttack/SuperAttackParty.cs
  Assets/5Adachi/Scripts/BossSuperAttack/SuperAttackParty.cs.meta
  Assets/5Adachi/Scripts/BossSuperAttack/SuperAttackPrison.cs
  Assets/5Adachi/Scripts/BossSuperAttack/SuperAttackPrison.cs.meta
  Assets/5Adachi/Scripts/BossSuperAttack/SuperAttackRandom.cs
  Assets/5Adachi/Scripts/BossSuperAttack/SuperAttackRandom.cs.meta
  Assets/5Adachi/Scripts/BossSuperAttack/SuperAttackRebound.cs
  Assets/5Adachi/Scripts/BossSuperAttack/SuperAttackRebound.cs.meta
  Assets/5Adachi/Scripts/BossSuperAttack/SuperAttackRestriction.cs
  Assets/5Adachi/Scripts/BossSuperAttack/SuperAttackRestriction.cs.meta
  Assets/5Adachi/Scripts/BossSuperAttack/SuperAttackSpiral.cs
  Assets/5Adachi/Scripts/BossSuperAttack/SuperAttackSpiral.cs.meta
  Assets/5Adachi/Scripts/BossSuperAttack/SuperAttackWindmill.cs
  Assets/5Adachi/Scripts/BossSuperAttack/SuperAttackWindmill.cs.meta
  Assets/5Adachi/Scripts/BossSuperAttack/TestSpecialAttack.cs
  Assets/5Adachi/Scripts/BossSuperAttack/TestSpecialAttack.cs.meta
  Assets/5Adachi/Scripts/PlayerBulletScripts.meta
  Assets/5Adachi/Scripts/PlayerBulletScripts/PlayerBulletFollow.cs
  Assets/5Adachi/Scripts/PlayerBulletScripts/PlayerBulletFollow.cs.meta
  Assets/5Adachi/Scripts/PlayerBulletScripts/PlayerBulletStraight.cs
  Assets/5Adachi/Scripts/PlayerBulletScripts/PlayerBulletStraight.cs.meta
  Assets/5Adachi/Square.prefab
Labels: 機能 プログラム など :memo:, 完了 :ballot_box_with_check:, 未完了 :x:

#147 不具合の修正
  Assets/5Adachi/Scenes/TestSceneAdachi.unity
  Assets/5Adachi/Scripts/BossNormalAttack/BossNormalAttack01.cs
  Assets/5Adachi/Scripts/BossNormalAttack/BossNormalAttack02.cs
  Assets/5Adachi/Scripts/BossNormalAttack/BossNormalAttack03.cs
  Assets/5Adachi/Scripts/BossSuperAttack/SuperAttackDelayFollow.cs
  Assets/5Adachi/Scripts/BossSuperAttack/SuperAttackEightShape.cs
  Assets/5Adachi/Scripts/BossSuperAttack/SuperAttackFirework.cs
  Assets/5Adachi/Scripts/BossSuperAttack/SuperAttackParty.cs
  Assets/5Adachi/Scripts/BossSuperAttack/SuperAttackPrison.cs
  Assets/5Adachi/Scripts/BossSuperAttack/SuperAttackRandom.cs
  Assets/5Adachi/Scripts/BossSuperAttack/SuperAttackRebound.cs
  Assets/5Adachi/Scripts/BossSuperAttack/SuperAttackRestriction.cs
  Assets/5Adachi/Scripts/BossSuperAttack/SuperAttackSpiral.cs
  Assets/5Adachi/Scripts/BossSuperAttack/SuperAttackWindmill.cs
Labels: 機能 プログラム など :memo:, 不具合修正 :wrench:, 未完了 :x:

#148 音を実装
  Assets/1Ito/Scripts Ito/ScriptableObject/PoolObjectParam.asset
  Assets/2Kanbara/Audio/AudioClip/1upAudio.wav
  Assets/2Kanbara/Audio/AudioClip/1upAudio.wav.meta
  Assets/2Kanbara/Audio/AudioClip/BombChildAudio.wav
  Assets/2Kanbara/Audio/AudioClip/BombChildAudio.wav.meta
  Assets/2Kanbara/Audio/AudioClip/BombItemGetAudio.wav
  Assets/2Kanbara/Audio/AudioClip/BombItemGetAudio.wav.meta
  Assets/2Kanbara/Audio/AudioClip/BombShotAudio.mp3
  Assets/2Kanbara/Audio/AudioClip/BombShotAudio.mp3.meta
  Assets/2Kanbara/Audio/AudioClip/ChargeShot.wav
  Assets/2Kanbara/Audio/AudioClip/ChargeShotAudio.wav
  Assets/2Kanbara/Audio/AudioClip/ChargeShotAudio.wav.meta
  Assets/2Kanbara/Audio/AudioClip/DeathAudio.wav
  Assets/2Kanbara/Audio/AudioClip/DeathAudio.wav.meta
  Assets/2Kanbara/Audio/AudioClip/InvincibleAudio.wav
  Assets/2Kanbara/Audio/AudioClip/InvincibleAudio.wav.meta
  Assets/2Kanbara/Audio/AudioClip/ItemGetAudio.wav
  Assets/2Kanbara/Audio/AudioClip/ItemGetAudio.wav.meta
  Assets/2Kanbara/Audio/AudioClip/LevelUp.wav
  Assets/2Kanbara/Audio/AudioClip/LevelUp.wav.meta
  Assets/2Kanbara/Audio/AudioClip/PlayerAttackAudio.wav
  Assets/2Kanbara/Audio/AudioClip/PlayerAttackAudio.wav.meta
  Assets/2Kanbara/Prefab Kanbara/Player/Player1.prefab
  Assets/2Kanbara/Prefab Kanbara/Player/Player1.prefab.meta
  Assets/2Kanbara/Prefab Kanbara/Player/Player2.prefab
  Assets/2Kanbara/Prefab Kanbara/Player/Player2.prefab.meta
  Assets/2Kanbara/Scenes Kanbara/PlayerMovement.unity
  Assets/2Kanbara/Scripts Kanbara/Item/ItemBase.cs
  Assets/2Kanbara/Scripts Kanbara/Player/Player1.cs
  Assets/2Kanbara/Scripts Kanbara/Player/Player2.cs
  Assets/2Kanbara/Scripts Kanbara/Player/PlayerBase.cs
  Assets/5Adachi/Scripts/PlayerBulletScripts/PlayerBulletFollow.cs
  Assets/6Kondo/Prefabs/Bomb01Child.prefab
  Assets/6Kondo/Prefabs/Bomb02Child.prefab
  Assets/6Kondo/Prefabs/Player01Bomb.prefab
  Assets/6Kondo/Prefabs/Player02Bomb.prefab
  Assets/6Kondo/Scripts/Bomb/Player01Bomb.cs
  Assets/6Kondo/Scripts/Bomb/Player02Bomb.cs
  Assets/6Kondo/Scripts/UIManager.cs
Labels: 機能 プログラム など :memo:, 不具合修正 :wrench:, 機能の修正 :toolbox:, 完了 :ballot_box_with_check:

#151 シーンくみ上げwip
  Assets/1Ito/Prefabs/===Managers===.prefab
  Assets/1Ito/Scripts Ito/Manager/GameManager.cs
  Assets/1Ito/Scripts Ito/Manager/PhaseNovelManager.cs
  Assets/1Ito/Scripts Ito/ScriptableObject/StageParam.cs
  Assets/2Kanbara/Scripts Kanbara/Player/PlayerBase.cs
  Assets/6Kondo/Scripts/UIManager.cs
  Assets/MasterScene/Stage1/Stage1Player1.unity
Labels: 機能 プログラム など :memo:, 不具合修正 :wrench:, 機能の修正 :toolbox:

#153 チュートリアルwip
  Assets/6Kondo/Animation/StageSelectButton.controller
  Assets/6Kondo/Animation/StageSelectButton.controller.meta
  Assets/6Kondo/Animation/StageSelectMove.anim
  Assets/6Kondo/Animation/StageSelectMove.anim.meta
  Assets/6Kondo/Animation/TutorialClear.anim
  Assets/6Kondo/Animation/TutorialClear.anim.meta
  Assets/6Kondo/Animation/TutorialClearPanel.controller
  Assets/6Kondo/Animation/TutorialClearPanel.controller.meta
  Assets/6Kondo/Scenes/ControllerTutorialPlayer1Stage.unity
  Assets/6Kondo/Scenes/ControllerTutorialPlayer1Stage.unity.meta
  Assets/6Kondo/Scenes/ControllerTutorialPlayer2Stage.unity
  Assets/6Kondo/Scenes/ControllerTutorialPlayer2Stage.unity.meta
  Assets/6Kondo/Scenes/KeybordTutorialPlayer1Stage.unity
  Assets/6Kondo/Scenes/KeybordTutorialPlayer1Stage.unity.meta
  Assets/6Kondo/Scenes/KeybordTutorialPlayer2Stage.unity
  Assets/6Kondo/Scenes/KeybordTutorialPlayer2Stage.unity.meta
  Assets/6Kondo/Scenes/TestScene.unity
  Assets/6Kondo/Scripts/PlayerTutorialTriger.cs
  Assets/6Kondo/Scripts/PlayerTutorialTriger.cs.meta
  Assets/6Kondo/Scripts/Tutorial.cs
  Assets/6Kondo/Scripts/Tutorial.cs.meta
  Assets/6Kondo/Sound/TutorialTaskClearSound.wav
  Assets/6Kondo/Sound/TutorialTaskClearSound.wav.meta
  Assets/6Kondo/Sprites/PlayerBulletSprites.meta
  Assets/6Kondo/Sprites/PlayerBulletSprites/Player02FallowBullet.png
  Assets/6Kondo/Sprites/PlayerBulletSprites/Player02FallowBullet.png.meta
  Assets/6Kondo/Sprites/PlayerBulletSprites/Player02MainBullet.PNG
  Assets/6Kondo/Sprites/PlayerBulletSprites/Player02MainBullet.PNG.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: 機能 プログラム など :memo:, 不具合発見 :bug:, 仕様 デザイン など :art:, 未完了 :x:

#155 ステージセレクト画面にボタンを追加
  Assets/6Kondo/Animation/StageSelectMove.anim
  Assets/MasterScene/StageSelectPlayer1.unity
  Assets/MasterScene/StageSelectPlayer2.unity
Labels: 機能 プログラム など :memo:, 仕様 デザイン など :art:, 完了 :ballot_box_with_check:

#154 チュートリアルステージ完成
  Assets/6Kondo/Scenes/ControllerTutorialPlayer1Stage.unity
  Assets/6Kondo/Scenes/ControllerTutorialPlayer2Stage.unity
  Assets/6Kondo/Scenes/KeybordTutorialPlayer1Stage.unity
  Assets/6Kondo/Scenes/KeybordTutorialPlayer2Stage.unity
  Assets/6Kondo/Scripts/Tutorial.cs
Labels: 機能 プログラム など :memo:, 仕様 デザイン など :art:, 完了 :ballot_box_with_check:

#159 チュートリアル、UIマネージャーの修正
  Assets/6Kondo/Scenes/ControllerTutorialPlayer1Stage.unity
  Assets/6Kondo/Scenes/ControllerTutorialPlayer2Stage.unity
  Assets/6Kondo/Scenes/KeybordTutorialPlayer1Stage.unity
  Assets/6Kondo/Scenes/KeybordTutorialPlayer2Stage.unity
  Assets/6Kondo/Scripts/Tutorial.cs
  Assets/6Kondo/Scripts/UIManager.cs
Labels: 機能 プログラム など :memo:, 機能の修正 :toolbox:, 完了 :ballot_box_with_check:

#160 チュートリアル修正
  Assets/6Kondo/Prefabs/ControllerTutorialCanvas.prefab
  Assets/6Kondo/Prefabs/ControllerTutorialCanvas.prefab.meta
  Assets/6Kondo/Prefabs/KeybordTutorialCanvas.prefab
  Assets/6Kondo/Prefabs/KeybordTutorialCanvas.prefab.meta
  Assets/6Kondo/Scenes/ControllerTutorialPlayer1Stage.unity
  Assets/6Kondo/Scenes/ControllerTutorialPlayer2Stage.unity
  Assets/6Kondo/Scenes/KeybordTutorialPlayer1Stage.unity
  Assets/6Kondo/Scenes/KeybordTutorialPlayer2Stage.unity
Labels: 仕様 デザイン など :art:, 機能の修正 :toolbox:

#161 チュートリアル修正
  Assets/MasterScene/Tutorial/ControllerTutorialPlayer2Stage.unity
  Assets/MasterScene/Tutorial/KeybordTutorialPlayer1Stage.unity
Labels: 機能 プログラム など :memo:, 不具合修正 :wrench:, 完了 :ballot_box_with_check:

#162 ボスコントローラー作成
  Assets/1Ito/ScenesIto/TestIto.unity
  Assets/1Ito/Scripts Ito/Boss.meta
  Assets/1Ito/Scripts Ito/Boss/BossController.cs
  Assets/1Ito/Scripts Ito/Boss/BossController.cs.meta
  Assets/1Ito/Scripts Ito/Boss/BossData.cs
  Assets/1Ito/Scripts Ito/Boss/BossData.cs.meta
  Assets/1Ito/Scripts Ito/Enemy/EnemyBase.cs
  Assets/1Ito/Scripts Ito/Enemy/TestEnemy01.cs
  Assets/1Ito/Scripts Ito/Manager/Editor/GameManagerEditor.cs
  Assets/1Ito/Scripts Ito/Manager/GameManager.cs
  Assets/1Ito/Scripts Ito/Manager/SceneManager/SceneLoder.cs
  Assets/1Ito/Scripts Ito/ScriptableObject/StageParam.cs
  Assets/5Adachi/Scripts/BossSuperAttack/TestSpecialAttack.cs
Labels: 機能 プログラム など :memo:, 完了 :ballot_box_with_check:

#165 弾幕のspriteの追加
  Assets/3Wada/Scenes Wada/Test Wada.unity
  Assets/3Wada/Sprites/EnemyBulletSprites/BossDefaultBulet4.png
  Assets/3Wada/Sprites/EnemyBulletSprites/BossDefaultBulet4.png.meta
  Assets/3Wada/Sprites/EnemyBulletSprites/BossDefaultBulet5.png
  Assets/3Wada/Sprites/EnemyBulletSprites/BossDefaultBulet5.png.meta
  Assets/3Wada/Sprites/EnemyBulletSprites/BossDefaultBulet6.png
  Assets/3Wada/Sprites/EnemyBulletSprites/BossDefaultBulet6.png.meta
  Assets/3Wada/Sprites/EnemyBulletSprites/BossDefaultBulet7.png
  Assets/3Wada/Sprites/EnemyBulletSprites/BossDefaultBulet7.png.meta
Labels: 仕様 デザイン など :art:
